-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity g_sum is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    x_ce0 : OUT STD_LOGIC;
    x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    y_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    y_ce0 : OUT STD_LOGIC;
    y_we0 : OUT STD_LOGIC;
    y_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    y_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of g_sum is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal k_23_fu_117_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal k_23_reg_196 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_123_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_reg_201 : STD_LOGIC_VECTOR (63 downto 0);
    signal exitcond2_fu_111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_24_fu_134_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_24_reg_214 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_cast_fu_152_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_cast_reg_219 : STD_LOGIC_VECTOR (6 downto 0);
    signal exitcond1_fu_128_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_k_9_fu_162_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal b_k_9_reg_227 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal exitcond_fu_156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_addr_2_reg_237 : STD_LOGIC_VECTOR (3 downto 0);
    signal k_reg_71 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal k_1_reg_82 : STD_LOGIC_VECTOR (2 downto 0);
    signal b_k_reg_93 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_155_fu_183_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_156_fu_188_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_157_fu_104_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_169_fu_140_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_144_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp1_fu_168_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp1_cast_fu_174_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_154_fu_178_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);

    component lenetSynthMatlab_bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    lenetSynthMatlab_bkb_U14 : component lenetSynthMatlab_bkb
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => y_q0,
        din1 => x_q0,
        dout => tmp_157_fu_104_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    b_k_reg_93_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_128_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                b_k_reg_93 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                b_k_reg_93 <= b_k_9_reg_227;
            end if; 
        end if;
    end process;

    k_1_reg_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond2_fu_111_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                k_1_reg_82 <= ap_const_lv3_0;
            elsif (((exitcond_fu_156_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                k_1_reg_82 <= k_24_reg_214;
            end if; 
        end if;
    end process;

    k_reg_71_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                k_reg_71 <= k_23_reg_196;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                k_reg_71 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                b_k_9_reg_227 <= b_k_9_fu_162_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                k_23_reg_196 <= k_23_fu_117_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                k_24_reg_214 <= k_24_fu_134_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_128_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    tmp_cast_reg_219(5 downto 4) <= tmp_cast_fu_152_p1(5 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond2_fu_111_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    tmp_reg_201(4 downto 0) <= tmp_fu_123_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_fu_156_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                y_addr_2_reg_237 <= tmp_156_fu_188_p1(4 - 1 downto 0);
            end if;
        end if;
    end process;
    tmp_reg_201(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";
    tmp_cast_reg_219(3 downto 0) <= "0000";
    tmp_cast_reg_219(6) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond2_fu_111_p2, ap_CS_fsm_state4, exitcond1_fu_128_p2, ap_CS_fsm_state5, exitcond_fu_156_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond2_fu_111_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state4 => 
                if (((exitcond1_fu_128_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((exitcond_fu_156_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4, exitcond1_fu_128_p2)
    begin
        if ((((exitcond1_fu_128_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, exitcond1_fu_128_p2)
    begin
        if (((exitcond1_fu_128_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    b_k_9_fu_162_p2 <= std_logic_vector(unsigned(b_k_reg_93) + unsigned(ap_const_lv5_1));
    exitcond1_fu_128_p2 <= "1" when (k_1_reg_82 = ap_const_lv3_4) else "0";
    exitcond2_fu_111_p2 <= "1" when (k_reg_71 = ap_const_lv5_10) else "0";
    exitcond_fu_156_p2 <= "1" when (b_k_reg_93 = ap_const_lv5_10) else "0";
    k_23_fu_117_p2 <= std_logic_vector(unsigned(k_reg_71) + unsigned(ap_const_lv5_1));
    k_24_fu_134_p2 <= std_logic_vector(unsigned(k_1_reg_82) + unsigned(ap_const_lv3_1));
    tmp1_cast_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_168_p2),7));
    tmp1_fu_168_p2 <= (b_k_reg_93 xor ap_const_lv5_10);
    tmp_154_fu_178_p2 <= std_logic_vector(unsigned(tmp1_cast_fu_174_p1) + unsigned(tmp_cast_reg_219));
    tmp_155_fu_183_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_154_fu_178_p2),64));
    tmp_156_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_k_reg_93),64));
    tmp_169_fu_140_p1 <= k_1_reg_82(2 - 1 downto 0);
    tmp_cast_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_144_p3),7));
    tmp_fu_123_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_reg_71),64));
    tmp_s_fu_144_p3 <= (tmp_169_fu_140_p1 & ap_const_lv4_0);

    x_address0_assign_proc : process(ap_CS_fsm_state2, tmp_fu_123_p1, ap_CS_fsm_state5, tmp_155_fu_183_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            x_address0 <= tmp_155_fu_183_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            x_address0 <= tmp_fu_123_p1(7 - 1 downto 0);
        else 
            x_address0 <= "XXXXXXX";
        end if; 
    end process;


    x_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            x_ce0 <= ap_const_logic_1;
        else 
            x_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y_address0_assign_proc : process(tmp_reg_201, ap_CS_fsm_state5, y_addr_2_reg_237, ap_CS_fsm_state3, ap_CS_fsm_state6, tmp_156_fu_188_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            y_address0 <= y_addr_2_reg_237;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            y_address0 <= tmp_156_fu_188_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y_address0 <= tmp_reg_201(4 - 1 downto 0);
        else 
            y_address0 <= "XXXX";
        end if; 
    end process;


    y_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            y_ce0 <= ap_const_logic_1;
        else 
            y_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y_d0_assign_proc : process(x_q0, ap_CS_fsm_state3, ap_CS_fsm_state6, tmp_157_fu_104_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            y_d0 <= tmp_157_fu_104_p2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y_d0 <= x_q0;
        else 
            y_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    y_we0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            y_we0 <= ap_const_logic_1;
        else 
            y_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
