# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.cache/wt [current_project]
set_property parent.project_path /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/ip
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet_100MHz/impl/ip
} [current_project]
set_property ip_output_repo /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/tyrian/nnproject/checkerRow.coe
add_files /home/tyrian/nnproject/checker4Row.coe
add_files /home/tyrian/testROM.coe
read_vhdl -library xil_defaultlib {
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/Part3/BBUART_TX.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/Part3/MLUART_RX.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/Part3/UART.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/Part3/fall_edge_det.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/new/lenet5top.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/Part3/rise_edge_det.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/Part3/sig_stretcher.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/Part3/synchro_2s.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/imports/Part3/fifo.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/new/serializer.vhd
  /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/new/UART_checker.vhd
}
read_ip -quiet /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/lenetSynthMatlab_0_2/lenetSynthMatlab_0.xci
set_property used_in_implementation false [get_files -all /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/lenetSynthMatlab_0_2/constraints/lenetSynthMatlab_ooc.xdc]

read_ip -quiet /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/image_ram/image_ram.xci
set_property used_in_implementation false [get_files -all /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/image_ram/image_ram_ooc.xdc]

read_ip -quiet /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/score_ram/score_ram.xci
set_property used_in_implementation false [get_files -all /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/score_ram/score_ram_ooc.xdc]

read_ip -quiet /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/testROM/testROM.xci
set_property used_in_implementation false [get_files -all /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/sources_1/ip/testROM/testROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/tyrian/nnproject/lenet58BitFloatMod/lenet58BitFloatMod.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top lenet5top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lenet5top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lenet5top_utilization_synth.rpt -pb lenet5top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
