// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module g_sum (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        y_address0,
        y_ce0,
        y_we0,
        y_d0,
        y_q0
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [3:0] y_address0;
output   y_ce0;
output   y_we0;
output  [31:0] y_d0;
input  [31:0] y_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] x_address0;
reg x_ce0;
reg[3:0] y_address0;
reg y_ce0;
reg y_we0;
reg[31:0] y_d0;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] k_23_fu_114_p2;
reg   [4:0] k_23_reg_193;
wire    ap_CS_fsm_state2;
wire   [63:0] tmp_fu_120_p1;
reg   [63:0] tmp_reg_198;
wire   [0:0] exitcond2_fu_108_p2;
wire   [2:0] k_24_fu_131_p2;
reg   [2:0] k_24_reg_211;
wire    ap_CS_fsm_state4;
wire   [6:0] tmp_cast_fu_149_p1;
reg   [6:0] tmp_cast_reg_216;
wire   [0:0] exitcond1_fu_125_p2;
wire   [4:0] b_k_9_fu_159_p2;
reg   [4:0] b_k_9_reg_224;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_fu_153_p2;
reg   [3:0] y_addr_2_reg_234;
reg   [31:0] x_load_2_reg_239;
wire    ap_CS_fsm_state6;
reg   [31:0] y_load_reg_244;
wire   [31:0] grp_fu_104_p2;
reg   [31:0] tmp_157_reg_249;
wire    ap_CS_fsm_state11;
reg   [4:0] k_reg_71;
wire    ap_CS_fsm_state3;
reg   [2:0] k_1_reg_82;
reg   [4:0] b_k_reg_93;
wire    ap_CS_fsm_state12;
wire   [63:0] tmp_155_fu_180_p1;
wire   [63:0] tmp_156_fu_185_p1;
wire    ap_CS_fsm_state7;
wire   [1:0] tmp_169_fu_137_p1;
wire   [5:0] tmp_s_fu_141_p3;
wire   [4:0] tmp1_fu_165_p2;
wire   [6:0] tmp1_cast_fu_171_p1;
wire   [6:0] tmp_154_fu_175_p2;
reg   [11:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
end

lenetSynthMatlab_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lenetSynthMatlab_bkb_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(y_load_reg_244),
    .din1(x_load_2_reg_239),
    .ce(1'b1),
    .dout(grp_fu_104_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_125_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        b_k_reg_93 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        b_k_reg_93 <= b_k_9_reg_224;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        k_1_reg_82 <= 3'd0;
    end else if (((exitcond_fu_153_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        k_1_reg_82 <= k_24_reg_211;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        k_reg_71 <= k_23_reg_193;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_reg_71 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        b_k_9_reg_224 <= b_k_9_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        k_23_reg_193 <= k_23_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        k_24_reg_211 <= k_24_fu_131_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_157_reg_249 <= grp_fu_104_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_125_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_cast_reg_216[5 : 4] <= tmp_cast_fu_149_p1[5 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_108_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_reg_198[4 : 0] <= tmp_fu_120_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_load_2_reg_239 <= x_q0;
        y_load_reg_244 <= y_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_153_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        y_addr_2_reg_234 <= tmp_156_fu_185_p1;
    end
end

always @ (*) begin
    if ((((exitcond1_fu_125_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_125_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address0 = tmp_155_fu_180_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_address0 = tmp_fu_120_p1;
    end else begin
        x_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        x_ce0 = 1'b1;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        y_address0 = y_addr_2_reg_234;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        y_address0 = tmp_156_fu_185_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y_address0 = tmp_reg_198;
    end else begin
        y_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state3))) begin
        y_ce0 = 1'b1;
    end else begin
        y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        y_d0 = tmp_157_reg_249;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y_d0 = x_q0;
    end else begin
        y_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state3))) begin
        y_we0 = 1'b1;
    end else begin
        y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond2_fu_108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond1_fu_125_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond_fu_153_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign b_k_9_fu_159_p2 = (b_k_reg_93 + 5'd1);

assign exitcond1_fu_125_p2 = ((k_1_reg_82 == 3'd4) ? 1'b1 : 1'b0);

assign exitcond2_fu_108_p2 = ((k_reg_71 == 5'd16) ? 1'b1 : 1'b0);

assign exitcond_fu_153_p2 = ((b_k_reg_93 == 5'd16) ? 1'b1 : 1'b0);

assign k_23_fu_114_p2 = (k_reg_71 + 5'd1);

assign k_24_fu_131_p2 = (k_1_reg_82 + 3'd1);

assign tmp1_cast_fu_171_p1 = tmp1_fu_165_p2;

assign tmp1_fu_165_p2 = (b_k_reg_93 ^ 5'd16);

assign tmp_154_fu_175_p2 = (tmp1_cast_fu_171_p1 + tmp_cast_reg_216);

assign tmp_155_fu_180_p1 = tmp_154_fu_175_p2;

assign tmp_156_fu_185_p1 = b_k_reg_93;

assign tmp_169_fu_137_p1 = k_1_reg_82[1:0];

assign tmp_cast_fu_149_p1 = tmp_s_fu_141_p3;

assign tmp_fu_120_p1 = k_reg_71;

assign tmp_s_fu_141_p3 = {{tmp_169_fu_137_p1}, {4'd0}};

always @ (posedge ap_clk) begin
    tmp_reg_198[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    tmp_cast_reg_216[3:0] <= 4'b0000;
    tmp_cast_reg_216[6] <= 1'b0;
end

endmodule //g_sum
