# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/c_sum.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/d_sum.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/f_sum.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/g_sum.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_Aem.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_CeG.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_DeQ.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_Ee0.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_Ffa.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_bkb.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_cud.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_dEe.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_eOg.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_fYi.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_g8j.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_hbi.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_ibs.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_jbC.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_kbM.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_lbW.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_mb6.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_ncg.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_ocq.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_pcA.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_qcK.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_rcU.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_sc4.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_tde.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_udo.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_vdy.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_wdI.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_yd2.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab_zec.vhd
  /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/sum.vhd
}
read_ip -quiet /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/project.srcs/sources_1/ip/lenetSynthMatlab_ap_fcmp_0_no_dsp_32/lenetSynthMatlab_ap_fcmp_0_no_dsp_32.xci

read_ip -quiet /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/project.srcs/sources_1/ip/lenetSynthMatlab_ap_uitofp_1_no_dsp_32/lenetSynthMatlab_ap_uitofp_1_no_dsp_32.xci

read_ip -quiet /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/project.srcs/sources_1/ip/lenetSynthMatlab_ap_fmul_0_max_dsp_32/lenetSynthMatlab_ap_fmul_0_max_dsp_32.xci

read_ip -quiet /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/project.srcs/sources_1/ip/lenetSynthMatlab_ap_fadd_2_full_dsp_32/lenetSynthMatlab_ap_fadd_2_full_dsp_32.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab.xdc
set_property used_in_implementation false [get_files /home/tyrian/nnproject/hls8BitFloatMod/Lenet5_50MHz/impl/vhdl/lenetSynthMatlab.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top lenetSynthMatlab -part xc7a100tcsg324-1 -directive sdx_optimization_effort_high -no_iobuf -mode out_of_context


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lenetSynthMatlab.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lenetSynthMatlab_utilization_synth.rpt -pb lenetSynthMatlab_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
