// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module d_sum (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        y_address0,
        y_ce0,
        y_we0,
        y_d0,
        y_q0
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [2:0] y_address0;
output   y_ce0;
output   y_we0;
output  [31:0] y_d0;
input  [31:0] y_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] x_address0;
reg x_ce0;
reg[2:0] y_address0;
reg y_ce0;
reg y_we0;
reg[31:0] y_d0;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] k_27_fu_110_p2;
reg   [2:0] k_27_reg_209;
wire    ap_CS_fsm_state2;
wire   [63:0] tmp_fu_116_p1;
reg   [63:0] tmp_reg_214;
wire   [0:0] exitcond2_fu_104_p2;
wire   [2:0] k_28_fu_127_p2;
reg   [2:0] k_28_reg_227;
wire    ap_CS_fsm_state4;
wire   [5:0] tmp_s_fu_159_p2;
reg   [5:0] tmp_s_reg_232;
wire   [0:0] exitcond1_fu_121_p2;
wire   [2:0] b_k_12_fu_175_p2;
reg   [2:0] b_k_12_reg_240;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_fu_169_p2;
reg   [2:0] y_addr_4_reg_250;
reg   [31:0] x_load_4_reg_255;
wire    ap_CS_fsm_state6;
reg   [31:0] y_load_reg_260;
wire   [31:0] grp_fu_100_p2;
reg   [31:0] tmp_147_reg_265;
wire    ap_CS_fsm_state11;
reg   [2:0] k_reg_67;
wire    ap_CS_fsm_state3;
reg   [2:0] k_1_reg_78;
reg   [2:0] b_k_reg_89;
wire    ap_CS_fsm_state12;
wire   [63:0] tmp_145_fu_196_p1;
wire   [63:0] tmp_146_fu_201_p1;
wire    ap_CS_fsm_state7;
wire   [1:0] tmp_153_fu_133_p1;
wire   [4:0] p_shl_fu_137_p3;
wire   [2:0] tmp_154_fu_149_p2;
wire   [5:0] p_shl_cast_fu_145_p1;
wire   [5:0] p_shl9_cast_fu_155_p1;
wire   [3:0] b_k_cast_fu_165_p1;
wire   [3:0] tmp1_fu_181_p2;
wire   [5:0] tmp1_cast_fu_187_p1;
wire   [5:0] tmp_144_fu_191_p2;
reg   [11:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
end

lenetSynthMatlab_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lenetSynthMatlab_bkb_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(y_load_reg_260),
    .din1(x_load_4_reg_255),
    .ce(1'b1),
    .dout(grp_fu_100_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_121_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        b_k_reg_89 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        b_k_reg_89 <= b_k_12_reg_240;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_104_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        k_1_reg_78 <= 3'd0;
    end else if (((exitcond_fu_169_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        k_1_reg_78 <= k_28_reg_227;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        k_reg_67 <= k_27_reg_209;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_reg_67 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        b_k_12_reg_240 <= b_k_12_fu_175_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        k_27_reg_209 <= k_27_fu_110_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        k_28_reg_227 <= k_28_fu_127_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_147_reg_265 <= grp_fu_100_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_104_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_reg_214[2 : 0] <= tmp_fu_116_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_121_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_s_reg_232[5 : 1] <= tmp_s_fu_159_p2[5 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_load_4_reg_255 <= x_q0;
        y_load_reg_260 <= y_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_169_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        y_addr_4_reg_250 <= tmp_146_fu_201_p1;
    end
end

always @ (*) begin
    if ((((exitcond1_fu_121_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_121_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_address0 = tmp_145_fu_196_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        x_address0 = tmp_fu_116_p1;
    end else begin
        x_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        x_ce0 = 1'b1;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        y_address0 = y_addr_4_reg_250;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        y_address0 = tmp_146_fu_201_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y_address0 = tmp_reg_214;
    end else begin
        y_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state3))) begin
        y_ce0 = 1'b1;
    end else begin
        y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        y_d0 = tmp_147_reg_265;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y_d0 = x_q0;
    end else begin
        y_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state3))) begin
        y_we0 = 1'b1;
    end else begin
        y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond2_fu_104_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond1_fu_121_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond_fu_169_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign b_k_12_fu_175_p2 = (b_k_reg_89 + 3'd1);

assign b_k_cast_fu_165_p1 = b_k_reg_89;

assign exitcond1_fu_121_p2 = ((k_1_reg_78 == 3'd4) ? 1'b1 : 1'b0);

assign exitcond2_fu_104_p2 = ((k_reg_67 == 3'd6) ? 1'b1 : 1'b0);

assign exitcond_fu_169_p2 = ((b_k_reg_89 == 3'd6) ? 1'b1 : 1'b0);

assign k_27_fu_110_p2 = (k_reg_67 + 3'd1);

assign k_28_fu_127_p2 = (k_1_reg_78 + 3'd1);

assign p_shl9_cast_fu_155_p1 = tmp_154_fu_149_p2;

assign p_shl_cast_fu_145_p1 = p_shl_fu_137_p3;

assign p_shl_fu_137_p3 = {{tmp_153_fu_133_p1}, {3'd0}};

assign tmp1_cast_fu_187_p1 = tmp1_fu_181_p2;

assign tmp1_fu_181_p2 = (b_k_cast_fu_165_p1 + 4'd6);

assign tmp_144_fu_191_p2 = (tmp1_cast_fu_187_p1 + tmp_s_reg_232);

assign tmp_145_fu_196_p1 = tmp_144_fu_191_p2;

assign tmp_146_fu_201_p1 = b_k_reg_89;

assign tmp_153_fu_133_p1 = k_1_reg_78[1:0];

assign tmp_154_fu_149_p2 = k_1_reg_78 << 3'd1;

assign tmp_fu_116_p1 = k_reg_67;

assign tmp_s_fu_159_p2 = (p_shl_cast_fu_145_p1 - p_shl9_cast_fu_155_p1);

always @ (posedge ap_clk) begin
    tmp_reg_214[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    tmp_s_reg_232[0] <= 1'b0;
end

endmodule //d_sum
