webtalk_init -webtalk_dir /home/tyrian/nnproject/lenet5VHDL8Bit/lenet5VHDL8Bit.sim/sim_1/behav/xsim/xsim.dir/tb_lenet5_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec  9 22:31:46 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211622750_0_0_902" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ba252943-85dd-45e9-9ea1-872a1ce989dc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9e27ceeeac934189a7ce2f7b65fb1b52" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "27" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2561.969 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "78716555 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1439.32_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "128572_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1100171341 -regid "211622750_0_0_902" -xml /home/tyrian/nnproject/lenet5VHDL8Bit/lenet5VHDL8Bit.sim/sim_1/behav/xsim/xsim.dir/tb_lenet5_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/tyrian/nnproject/lenet5VHDL8Bit/lenet5VHDL8Bit.sim/sim_1/behav/xsim/xsim.dir/tb_lenet5_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/tyrian/nnproject/lenet5VHDL8Bit/lenet5VHDL8Bit.sim/sim_1/behav/xsim/xsim.dir/tb_lenet5_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
