# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tyrian/nnproject/lenet5VHDL8Bit/lenet5VHDL8Bit.srcs/sources_1/ip/lenetSynthMatlab_0/lenetSynthMatlab_0.xci
# IP: The module: 'lenetSynthMatlab_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tyrian/nnproject/lenet5VHDL8Bit/lenet5VHDL8Bit.srcs/sources_1/ip/lenetSynthMatlab_0/constraints/lenetSynthMatlab_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenetSynthMatlab_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tyrian/nnproject/lenet5VHDL8Bit/lenet5VHDL8Bit.srcs/sources_1/ip/lenetSynthMatlab_0/lenetSynthMatlab_0.xci
# IP: The module: 'lenetSynthMatlab_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tyrian/nnproject/lenet5VHDL8Bit/lenet5VHDL8Bit.srcs/sources_1/ip/lenetSynthMatlab_0/constraints/lenetSynthMatlab_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lenetSynthMatlab_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
