// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "d_sum.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic d_sum::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic d_sum::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<22> d_sum::ap_ST_fsm_state1 = "1";
const sc_lv<22> d_sum::ap_ST_fsm_state2 = "10";
const sc_lv<22> d_sum::ap_ST_fsm_state3 = "100";
const sc_lv<22> d_sum::ap_ST_fsm_state4 = "1000";
const sc_lv<22> d_sum::ap_ST_fsm_state5 = "10000";
const sc_lv<22> d_sum::ap_ST_fsm_state6 = "100000";
const sc_lv<22> d_sum::ap_ST_fsm_state7 = "1000000";
const sc_lv<22> d_sum::ap_ST_fsm_state8 = "10000000";
const sc_lv<22> d_sum::ap_ST_fsm_state9 = "100000000";
const sc_lv<22> d_sum::ap_ST_fsm_state10 = "1000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state11 = "10000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state12 = "100000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<22> d_sum::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<32> d_sum::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> d_sum::ap_const_lv32_1 = "1";
const sc_lv<1> d_sum::ap_const_lv1_0 = "0";
const sc_lv<32> d_sum::ap_const_lv32_2 = "10";
const sc_lv<32> d_sum::ap_const_lv32_3 = "11";
const sc_lv<1> d_sum::ap_const_lv1_1 = "1";
const sc_lv<32> d_sum::ap_const_lv32_A = "1010";
const sc_lv<32> d_sum::ap_const_lv32_B = "1011";
const sc_lv<32> d_sum::ap_const_lv32_12 = "10010";
const sc_lv<32> d_sum::ap_const_lv32_13 = "10011";
const sc_lv<32> d_sum::ap_const_lv32_14 = "10100";
const sc_lv<32> d_sum::ap_const_lv32_15 = "10101";
const sc_lv<3> d_sum::ap_const_lv3_0 = "000";
const sc_lv<6> d_sum::ap_const_lv6_4 = "100";
const sc_lv<6> d_sum::ap_const_lv6_3F = "111111";
const sc_lv<5> d_sum::ap_const_lv5_5 = "101";
const sc_lv<3> d_sum::ap_const_lv3_6 = "110";
const sc_lv<3> d_sum::ap_const_lv3_1 = "1";
const sc_lv<6> d_sum::ap_const_lv6_5 = "101";
const sc_lv<5> d_sum::ap_const_lv5_1 = "1";
const sc_lv<32> d_sum::ap_const_lv32_25 = "100101";
const sc_lv<64> d_sum::ap_const_lv64_FFFFFFE000000000 = "1111111111111111111111111110000000000000000000000000000000000000";
const sc_lv<32> d_sum::ap_const_lv32_7FFFFFF9 = "1111111111111111111111111111001";
const sc_lv<32> d_sum::ap_const_lv32_6 = "110";
const sc_lv<32> d_sum::ap_const_lv32_1D = "11101";
const sc_lv<32> d_sum::ap_const_lv32_FFFFFFE9 = "11111111111111111111111111101001";
const sc_lv<12> d_sum::ap_const_lv12_34 = "110100";
const sc_lv<32> d_sum::ap_const_lv32_8 = "1000";
const bool d_sum::ap_const_boolean_1 = true;

d_sum::d_sum(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lenetSynthMatlab_dEe_U17 = new lenetSynthMatlab_dEe<1,9,5,4,3>("lenetSynthMatlab_dEe_U17");
    lenetSynthMatlab_dEe_U17->clk(ap_clk);
    lenetSynthMatlab_dEe_U17->reset(ap_rst);
    lenetSynthMatlab_dEe_U17->start(grp_fu_199_ap_start);
    lenetSynthMatlab_dEe_U17->done(grp_fu_199_ap_done);
    lenetSynthMatlab_dEe_U17->din0(grp_fu_199_p0);
    lenetSynthMatlab_dEe_U17->din1(grp_fu_199_p1);
    lenetSynthMatlab_dEe_U17->ce(ap_var_for_const0);
    lenetSynthMatlab_dEe_U17->dout(grp_fu_199_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_X_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( tmp_s_fu_220_p1 );
    sensitive << ( tmp_71_fu_472_p1 );

    SC_METHOD(thread_X_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_Y_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_64_fu_315_p1 );

    SC_METHOD(thread_Y_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Y_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( s_1_reg_142 );

    SC_METHOD(thread_Y_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_270_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_204_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_b3_phi_fu_178_p4);
    sensitive << ( b3_reg_173 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_204_p2 );

    SC_METHOD(thread_exitcond1_fu_204_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iy_reg_119 );

    SC_METHOD(thread_exitcond_fu_270_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( indvars_iv_reg_107 );
    sensitive << ( ix_1_cast_cast_fu_266_p1 );

    SC_METHOD(thread_grp_fu_199_ap_start);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_270_p2 );
    sensitive << ( ap_phi_mux_b3_phi_fu_178_p4 );
    sensitive << ( tmp_67_fu_283_p2 );

    SC_METHOD(thread_grp_fu_199_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_270_p2 );
    sensitive << ( ap_phi_mux_b3_phi_fu_178_p4 );
    sensitive << ( tmp_67_fu_283_p2 );
    sensitive << ( ix_1_reg_164 );

    SC_METHOD(thread_grp_fu_199_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_270_p2 );
    sensitive << ( ap_phi_mux_b3_phi_fu_178_p4 );
    sensitive << ( tmp_67_fu_283_p2 );

    SC_METHOD(thread_i_fu_320_p2);
    sensitive << ( iy_reg_119 );

    SC_METHOD(thread_indvars_iv_next2_fu_210_p2);
    sensitive << ( indvars_iv1_reg_96 );

    SC_METHOD(thread_indvars_iv_next_fu_326_p2);
    sensitive << ( indvars_iv_reg_107 );

    SC_METHOD(thread_ix_1_cast_cast_fu_266_p1);
    sensitive << ( ix_1_reg_164 );

    SC_METHOD(thread_ix_8_fu_225_p2);
    sensitive << ( ix_reg_131 );

    SC_METHOD(thread_ix_9_fu_276_p2);
    sensitive << ( ix_1_reg_164 );

    SC_METHOD(thread_ixstart_14_fu_462_p2);
    sensitive << ( tmp_143_cast_fu_458_p1 );
    sensitive << ( tmp_66_fu_449_p2 );

    SC_METHOD(thread_ixstart_15_fu_392_p2);
    sensitive << ( tmp_146_cast_fu_388_p1 );
    sensitive << ( tmp_69_fu_379_p2 );

    SC_METHOD(thread_ixstart_16_fu_289_p2);
    sensitive << ( ixstart_reg_153 );

    SC_METHOD(thread_ixstart_17_fu_301_p2);
    sensitive << ( ixstart_reg_153 );

    SC_METHOD(thread_ixstart_20_cast_fu_468_p1);
    sensitive << ( ixstart_14_fu_462_p2 );

    SC_METHOD(thread_ixstart_21_cast_fu_398_p1);
    sensitive << ( ixstart_15_fu_392_p2 );

    SC_METHOD(thread_ixstart_cast_fu_231_p2);
    sensitive << ( tmp_reg_545 );

    SC_METHOD(thread_mul4_fu_335_p1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( mul4_fu_335_p10 );

    SC_METHOD(thread_mul4_fu_335_p10);
    sensitive << ( ix_9_reg_573 );

    SC_METHOD(thread_mul4_fu_335_p2);
    sensitive << ( mul4_fu_335_p1 );

    SC_METHOD(thread_mul_fu_405_p1);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( mul_fu_405_p10 );

    SC_METHOD(thread_mul_fu_405_p10);
    sensitive << ( ix_9_reg_573 );

    SC_METHOD(thread_mul_fu_405_p2);
    sensitive << ( mul_fu_405_p1 );

    SC_METHOD(thread_p_s_fu_307_p3);
    sensitive << ( ixstart_16_fu_289_p2 );
    sensitive << ( tmp_70_fu_295_p2 );
    sensitive << ( ixstart_17_fu_301_p2 );

    SC_METHOD(thread_p_shl10_cast_fu_363_p1);
    sensitive << ( p_shl10_fu_355_p3 );

    SC_METHOD(thread_p_shl10_fu_355_p3);
    sensitive << ( tmp_97_fu_351_p1 );

    SC_METHOD(thread_p_shl11_cast_fu_375_p1);
    sensitive << ( p_shl11_fu_367_p3 );

    SC_METHOD(thread_p_shl11_fu_367_p3);
    sensitive << ( tmp_97_fu_351_p1 );

    SC_METHOD(thread_p_shl8_cast_fu_445_p1);
    sensitive << ( p_shl8_fu_437_p3 );

    SC_METHOD(thread_p_shl8_fu_437_p3);
    sensitive << ( tmp_95_fu_421_p1 );

    SC_METHOD(thread_p_shl_cast_fu_433_p1);
    sensitive << ( p_shl_fu_425_p3 );

    SC_METHOD(thread_p_shl_fu_425_p3);
    sensitive << ( tmp_95_fu_421_p1 );

    SC_METHOD(thread_s12_fu_258_p3);
    sensitive << ( tmp_94_fu_240_p3 );
    sensitive << ( s_4_fu_248_p2 );
    sensitive << ( s_16_cast_fu_254_p1 );

    SC_METHOD(thread_s_11_fu_236_p1);
    sensitive << ( X_q0 );

    SC_METHOD(thread_s_13_fu_493_p2);
    sensitive << ( X_q0 );
    sensitive << ( s_1_reg_142 );

    SC_METHOD(thread_s_14_fu_519_p2);
    sensitive << ( s_13_fu_493_p2 );

    SC_METHOD(thread_s_16_cast_fu_254_p1);
    sensitive << ( s_11_fu_236_p1 );

    SC_METHOD(thread_s_18_cast_fu_505_p2);
    sensitive << ( tmp_100_fu_481_p1 );
    sensitive << ( tmp_99_fu_477_p1 );

    SC_METHOD(thread_s_20_cast_fu_525_p1);
    sensitive << ( s_5_fu_499_p2 );

    SC_METHOD(thread_s_2_fu_529_p3);
    sensitive << ( tmp_103_fu_511_p3 );
    sensitive << ( s_14_fu_519_p2 );
    sensitive << ( s_20_cast_fu_525_p1 );

    SC_METHOD(thread_s_4_fu_248_p2);
    sensitive << ( X_q0 );

    SC_METHOD(thread_s_5_fu_499_p2);
    sensitive << ( tmp_102_fu_489_p1 );
    sensitive << ( tmp_101_fu_485_p1 );

    SC_METHOD(thread_tmp_100_fu_481_p1);
    sensitive << ( X_q0 );

    SC_METHOD(thread_tmp_101_fu_485_p1);
    sensitive << ( s_1_reg_142 );

    SC_METHOD(thread_tmp_102_fu_489_p1);
    sensitive << ( X_q0 );

    SC_METHOD(thread_tmp_103_fu_511_p3);
    sensitive << ( s_18_cast_fu_505_p2 );

    SC_METHOD(thread_tmp_143_cast_fu_458_p1);
    sensitive << ( tmp_52_fu_455_p1 );

    SC_METHOD(thread_tmp_146_cast_fu_388_p1);
    sensitive << ( tmp_53_fu_385_p1 );

    SC_METHOD(thread_tmp_52_fu_455_p1);
    sensitive << ( tmp_96_reg_609 );

    SC_METHOD(thread_tmp_53_fu_385_p1);
    sensitive << ( tmp_98_reg_599 );

    SC_METHOD(thread_tmp_64_fu_315_p1);
    sensitive << ( iy_reg_119 );

    SC_METHOD(thread_tmp_66_fu_449_p2);
    sensitive << ( p_shl_cast_fu_433_p1 );
    sensitive << ( p_shl8_cast_fu_445_p1 );

    SC_METHOD(thread_tmp_67_fu_283_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_270_p2 );
    sensitive << ( ap_phi_mux_b3_phi_fu_178_p4 );
    sensitive << ( ixstart_reg_153 );

    SC_METHOD(thread_tmp_69_fu_379_p2);
    sensitive << ( p_shl10_cast_fu_363_p1 );
    sensitive << ( p_shl11_cast_fu_375_p1 );

    SC_METHOD(thread_tmp_70_fu_295_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_270_p2 );
    sensitive << ( ap_phi_mux_b3_phi_fu_178_p4 );
    sensitive << ( tmp_67_fu_283_p2 );
    sensitive << ( ixstart_16_fu_289_p2 );

    SC_METHOD(thread_tmp_71_fu_472_p1);
    sensitive << ( ixstart_4_reg_186 );

    SC_METHOD(thread_tmp_94_fu_240_p3);
    sensitive << ( X_q0 );

    SC_METHOD(thread_tmp_95_fu_421_p1);
    sensitive << ( grp_fu_199_p2 );

    SC_METHOD(thread_tmp_97_fu_351_p1);
    sensitive << ( grp_fu_199_p2 );

    SC_METHOD(thread_tmp_99_fu_477_p1);
    sensitive << ( s_1_reg_142 );

    SC_METHOD(thread_tmp_fu_216_p1);
    sensitive << ( ix_reg_131 );

    SC_METHOD(thread_tmp_s_fu_220_p1);
    sensitive << ( indvars_iv1_reg_96 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_204_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_270_p2 );
    sensitive << ( ap_phi_mux_b3_phi_fu_178_p4 );
    sensitive << ( tmp_67_fu_283_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "d_sum_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, X_address0, "(port)X_address0");
    sc_trace(mVcdFile, X_ce0, "(port)X_ce0");
    sc_trace(mVcdFile, X_q0, "(port)X_q0");
    sc_trace(mVcdFile, Y_address0, "(port)Y_address0");
    sc_trace(mVcdFile, Y_ce0, "(port)Y_ce0");
    sc_trace(mVcdFile, Y_we0, "(port)Y_we0");
    sc_trace(mVcdFile, Y_d0, "(port)Y_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvars_iv_next2_fu_210_p2, "indvars_iv_next2_fu_210_p2");
    sc_trace(mVcdFile, indvars_iv_next2_reg_540, "indvars_iv_next2_reg_540");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_216_p1, "tmp_fu_216_p1");
    sc_trace(mVcdFile, tmp_reg_545, "tmp_reg_545");
    sc_trace(mVcdFile, exitcond1_fu_204_p2, "exitcond1_fu_204_p2");
    sc_trace(mVcdFile, ix_8_fu_225_p2, "ix_8_fu_225_p2");
    sc_trace(mVcdFile, ix_8_reg_555, "ix_8_reg_555");
    sc_trace(mVcdFile, ixstart_cast_fu_231_p2, "ixstart_cast_fu_231_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, s12_fu_258_p3, "s12_fu_258_p3");
    sc_trace(mVcdFile, ix_9_fu_276_p2, "ix_9_fu_276_p2");
    sc_trace(mVcdFile, ix_9_reg_573, "ix_9_reg_573");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond_fu_270_p2, "exitcond_fu_270_p2");
    sc_trace(mVcdFile, p_s_fu_307_p3, "p_s_fu_307_p3");
    sc_trace(mVcdFile, ap_phi_mux_b3_phi_fu_178_p4, "ap_phi_mux_b3_phi_fu_178_p4");
    sc_trace(mVcdFile, tmp_67_fu_283_p2, "tmp_67_fu_283_p2");
    sc_trace(mVcdFile, i_fu_320_p2, "i_fu_320_p2");
    sc_trace(mVcdFile, indvars_iv_next_fu_326_p2, "indvars_iv_next_fu_326_p2");
    sc_trace(mVcdFile, tmp_98_reg_599, "tmp_98_reg_599");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ixstart_21_cast_fu_398_p1, "ixstart_21_cast_fu_398_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_96_reg_609, "tmp_96_reg_609");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ixstart_20_cast_fu_468_p1, "ixstart_20_cast_fu_468_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, s_2_fu_529_p3, "s_2_fu_529_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, indvars_iv1_reg_96, "indvars_iv1_reg_96");
    sc_trace(mVcdFile, indvars_iv_reg_107, "indvars_iv_reg_107");
    sc_trace(mVcdFile, iy_reg_119, "iy_reg_119");
    sc_trace(mVcdFile, ix_reg_131, "ix_reg_131");
    sc_trace(mVcdFile, s_1_reg_142, "s_1_reg_142");
    sc_trace(mVcdFile, ixstart_reg_153, "ixstart_reg_153");
    sc_trace(mVcdFile, ixstart_4_reg_186, "ixstart_4_reg_186");
    sc_trace(mVcdFile, ix_1_reg_164, "ix_1_reg_164");
    sc_trace(mVcdFile, b3_reg_173, "b3_reg_173");
    sc_trace(mVcdFile, tmp_s_fu_220_p1, "tmp_s_fu_220_p1");
    sc_trace(mVcdFile, tmp_64_fu_315_p1, "tmp_64_fu_315_p1");
    sc_trace(mVcdFile, tmp_71_fu_472_p1, "tmp_71_fu_472_p1");
    sc_trace(mVcdFile, grp_fu_199_p0, "grp_fu_199_p0");
    sc_trace(mVcdFile, grp_fu_199_p1, "grp_fu_199_p1");
    sc_trace(mVcdFile, s_11_fu_236_p1, "s_11_fu_236_p1");
    sc_trace(mVcdFile, tmp_94_fu_240_p3, "tmp_94_fu_240_p3");
    sc_trace(mVcdFile, s_4_fu_248_p2, "s_4_fu_248_p2");
    sc_trace(mVcdFile, s_16_cast_fu_254_p1, "s_16_cast_fu_254_p1");
    sc_trace(mVcdFile, ix_1_cast_cast_fu_266_p1, "ix_1_cast_cast_fu_266_p1");
    sc_trace(mVcdFile, ixstart_16_fu_289_p2, "ixstart_16_fu_289_p2");
    sc_trace(mVcdFile, tmp_70_fu_295_p2, "tmp_70_fu_295_p2");
    sc_trace(mVcdFile, ixstart_17_fu_301_p2, "ixstart_17_fu_301_p2");
    sc_trace(mVcdFile, mul4_fu_335_p1, "mul4_fu_335_p1");
    sc_trace(mVcdFile, mul4_fu_335_p2, "mul4_fu_335_p2");
    sc_trace(mVcdFile, grp_fu_199_p2, "grp_fu_199_p2");
    sc_trace(mVcdFile, tmp_97_fu_351_p1, "tmp_97_fu_351_p1");
    sc_trace(mVcdFile, p_shl10_fu_355_p3, "p_shl10_fu_355_p3");
    sc_trace(mVcdFile, p_shl11_fu_367_p3, "p_shl11_fu_367_p3");
    sc_trace(mVcdFile, p_shl10_cast_fu_363_p1, "p_shl10_cast_fu_363_p1");
    sc_trace(mVcdFile, p_shl11_cast_fu_375_p1, "p_shl11_cast_fu_375_p1");
    sc_trace(mVcdFile, tmp_53_fu_385_p1, "tmp_53_fu_385_p1");
    sc_trace(mVcdFile, tmp_146_cast_fu_388_p1, "tmp_146_cast_fu_388_p1");
    sc_trace(mVcdFile, tmp_69_fu_379_p2, "tmp_69_fu_379_p2");
    sc_trace(mVcdFile, ixstart_15_fu_392_p2, "ixstart_15_fu_392_p2");
    sc_trace(mVcdFile, mul_fu_405_p1, "mul_fu_405_p1");
    sc_trace(mVcdFile, mul_fu_405_p2, "mul_fu_405_p2");
    sc_trace(mVcdFile, tmp_95_fu_421_p1, "tmp_95_fu_421_p1");
    sc_trace(mVcdFile, p_shl_fu_425_p3, "p_shl_fu_425_p3");
    sc_trace(mVcdFile, p_shl8_fu_437_p3, "p_shl8_fu_437_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_433_p1, "p_shl_cast_fu_433_p1");
    sc_trace(mVcdFile, p_shl8_cast_fu_445_p1, "p_shl8_cast_fu_445_p1");
    sc_trace(mVcdFile, tmp_52_fu_455_p1, "tmp_52_fu_455_p1");
    sc_trace(mVcdFile, tmp_143_cast_fu_458_p1, "tmp_143_cast_fu_458_p1");
    sc_trace(mVcdFile, tmp_66_fu_449_p2, "tmp_66_fu_449_p2");
    sc_trace(mVcdFile, ixstart_14_fu_462_p2, "ixstart_14_fu_462_p2");
    sc_trace(mVcdFile, tmp_102_fu_489_p1, "tmp_102_fu_489_p1");
    sc_trace(mVcdFile, tmp_101_fu_485_p1, "tmp_101_fu_485_p1");
    sc_trace(mVcdFile, tmp_100_fu_481_p1, "tmp_100_fu_481_p1");
    sc_trace(mVcdFile, tmp_99_fu_477_p1, "tmp_99_fu_477_p1");
    sc_trace(mVcdFile, s_18_cast_fu_505_p2, "s_18_cast_fu_505_p2");
    sc_trace(mVcdFile, s_13_fu_493_p2, "s_13_fu_493_p2");
    sc_trace(mVcdFile, s_5_fu_499_p2, "s_5_fu_499_p2");
    sc_trace(mVcdFile, tmp_103_fu_511_p3, "tmp_103_fu_511_p3");
    sc_trace(mVcdFile, s_14_fu_519_p2, "s_14_fu_519_p2");
    sc_trace(mVcdFile, s_20_cast_fu_525_p1, "s_20_cast_fu_525_p1");
    sc_trace(mVcdFile, grp_fu_199_ap_start, "grp_fu_199_ap_start");
    sc_trace(mVcdFile, grp_fu_199_ap_done, "grp_fu_199_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul4_fu_335_p10, "mul4_fu_335_p10");
    sc_trace(mVcdFile, mul_fu_405_p10, "mul_fu_405_p10");
#endif

    }
}

d_sum::~d_sum() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete lenetSynthMatlab_dEe_U17;
}

void d_sum::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void d_sum::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        b3_reg_173 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        b3_reg_173 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        indvars_iv1_reg_96 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        indvars_iv1_reg_96 = indvars_iv_next2_reg_540.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        indvars_iv_reg_107 = ap_const_lv6_4;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        indvars_iv_reg_107 = indvars_iv_next_fu_326_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        ix_1_reg_164 = ix_9_reg_573.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ix_1_reg_164 = ixstart_cast_fu_231_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ix_reg_131 = ap_const_lv6_3F;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ix_reg_131 = ix_8_reg_555.read();
    }
    if ((esl_seteq<1,1,1>(tmp_67_fu_283_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_phi_mux_b3_phi_fu_178_p4.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ixstart_4_reg_186 = p_s_fu_307_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        ixstart_4_reg_186 = ixstart_21_cast_fu_398_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        ixstart_4_reg_186 = ixstart_20_cast_fu_468_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        ixstart_reg_153 = ixstart_4_reg_186.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ixstart_reg_153 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        iy_reg_119 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        iy_reg_119 = i_fu_320_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        s_1_reg_142 = s_2_fu_529_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        s_1_reg_142 = s12_fu_258_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        indvars_iv_next2_reg_540 = indvars_iv_next2_fu_210_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ix_8_reg_555 = ix_8_fu_225_p2.read();
        tmp_reg_545 = tmp_fu_216_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_0))) {
        ix_9_reg_573 = ix_9_fu_276_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        tmp_96_reg_609 = mul_fu_405_p2.read().range(11, 8);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        tmp_98_reg_599 = mul4_fu_335_p2.read().range(11, 8);
    }
}

void d_sum::thread_X_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        X_address0 =  (sc_lv<5>) (tmp_71_fu_472_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        X_address0 =  (sc_lv<5>) (tmp_s_fu_220_p1.read());
    } else {
        X_address0 = "XXXXX";
    }
}

void d_sum::thread_X_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()))) {
        X_ce0 = ap_const_logic_1;
    } else {
        X_ce0 = ap_const_logic_0;
    }
}

void d_sum::thread_Y_address0() {
    Y_address0 =  (sc_lv<3>) (tmp_64_fu_315_p1.read());
}

void d_sum::thread_Y_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Y_ce0 = ap_const_logic_1;
    } else {
        Y_ce0 = ap_const_logic_0;
    }
}

void d_sum::thread_Y_d0() {
    Y_d0 = s_1_reg_142.read();
}

void d_sum::thread_Y_we0() {
    if ((esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        Y_we0 = ap_const_logic_1;
    } else {
        Y_we0 = ap_const_logic_0;
    }
}

void d_sum::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void d_sum::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void d_sum::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void d_sum::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void d_sum::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void d_sum::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void d_sum::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void d_sum::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void d_sum::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void d_sum::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void d_sum::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void d_sum::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void d_sum::thread_ap_phi_mux_b3_phi_fu_178_p4() {
    ap_phi_mux_b3_phi_fu_178_p4 = b3_reg_173.read();
}

void d_sum::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void d_sum::thread_exitcond1_fu_204_p2() {
    exitcond1_fu_204_p2 = (!iy_reg_119.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(iy_reg_119.read() == ap_const_lv3_6);
}

void d_sum::thread_exitcond_fu_270_p2() {
    exitcond_fu_270_p2 = (!ix_1_cast_cast_fu_266_p1.read().is_01() || !indvars_iv_reg_107.read().is_01())? sc_lv<1>(): sc_lv<1>(ix_1_cast_cast_fu_266_p1.read() == indvars_iv_reg_107.read());
}

void d_sum::thread_grp_fu_199_ap_start() {
    if (((esl_seteq<1,1,1>(tmp_67_fu_283_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_phi_mux_b3_phi_fu_178_p4.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) || 
         (esl_seteq<1,1,1>(ap_phi_mux_b3_phi_fu_178_p4.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())))) {
        grp_fu_199_ap_start = ap_const_logic_1;
    } else {
        grp_fu_199_ap_start = ap_const_logic_0;
    }
}

void d_sum::thread_grp_fu_199_p0() {
    grp_fu_199_p0 = (!ix_1_reg_164.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(ix_1_reg_164.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void d_sum::thread_grp_fu_199_p1() {
    grp_fu_199_p1 =  (sc_lv<4>) (ap_const_lv5_5);
}

void d_sum::thread_i_fu_320_p2() {
    i_fu_320_p2 = (!iy_reg_119.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(iy_reg_119.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void d_sum::thread_indvars_iv_next2_fu_210_p2() {
    indvars_iv_next2_fu_210_p2 = (!indvars_iv1_reg_96.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(indvars_iv1_reg_96.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void d_sum::thread_indvars_iv_next_fu_326_p2() {
    indvars_iv_next_fu_326_p2 = (!indvars_iv_reg_107.read().is_01() || !ap_const_lv6_5.is_01())? sc_lv<6>(): (sc_biguint<6>(indvars_iv_reg_107.read()) + sc_biguint<6>(ap_const_lv6_5));
}

void d_sum::thread_ix_1_cast_cast_fu_266_p1() {
    ix_1_cast_cast_fu_266_p1 = esl_zext<6,5>(ix_1_reg_164.read());
}

void d_sum::thread_ix_8_fu_225_p2() {
    ix_8_fu_225_p2 = (!ap_const_lv6_5.is_01() || !ix_reg_131.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_5) + sc_biguint<6>(ix_reg_131.read()));
}

void d_sum::thread_ix_9_fu_276_p2() {
    ix_9_fu_276_p2 = (!ix_1_reg_164.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(ix_1_reg_164.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void d_sum::thread_ixstart_14_fu_462_p2() {
    ixstart_14_fu_462_p2 = (!tmp_143_cast_fu_458_p1.read().is_01() || !tmp_66_fu_449_p2.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_143_cast_fu_458_p1.read()) + sc_biguint<7>(tmp_66_fu_449_p2.read()));
}

void d_sum::thread_ixstart_15_fu_392_p2() {
    ixstart_15_fu_392_p2 = (!tmp_146_cast_fu_388_p1.read().is_01() || !tmp_69_fu_379_p2.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_146_cast_fu_388_p1.read()) + sc_biguint<7>(tmp_69_fu_379_p2.read()));
}

void d_sum::thread_ixstart_16_fu_289_p2() {
    ixstart_16_fu_289_p2 = (!ixstart_reg_153.read().is_01() || !ap_const_lv32_6.is_01())? sc_lv<32>(): (sc_biguint<32>(ixstart_reg_153.read()) + sc_biguint<32>(ap_const_lv32_6));
}

void d_sum::thread_ixstart_17_fu_301_p2() {
    ixstart_17_fu_301_p2 = (!ixstart_reg_153.read().is_01() || !ap_const_lv32_FFFFFFE9.is_01())? sc_lv<32>(): (sc_biguint<32>(ixstart_reg_153.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFE9));
}

void d_sum::thread_ixstart_20_cast_fu_468_p1() {
    ixstart_20_cast_fu_468_p1 = esl_sext<32,7>(ixstart_14_fu_462_p2.read());
}

void d_sum::thread_ixstart_21_cast_fu_398_p1() {
    ixstart_21_cast_fu_398_p1 = esl_sext<32,7>(ixstart_15_fu_392_p2.read());
}

void d_sum::thread_ixstart_cast_fu_231_p2() {
    ixstart_cast_fu_231_p2 = (!ap_const_lv5_1.is_01() || !tmp_reg_545.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_1) + sc_biguint<5>(tmp_reg_545.read()));
}

void d_sum::thread_mul4_fu_335_p1() {
    mul4_fu_335_p1 =  (sc_lv<5>) (mul4_fu_335_p10.read());
}

void d_sum::thread_mul4_fu_335_p10() {
    mul4_fu_335_p10 = esl_zext<12,5>(ix_9_reg_573.read());
}

void d_sum::thread_mul4_fu_335_p2() {
    mul4_fu_335_p2 = (!ap_const_lv12_34.is_01() || !mul4_fu_335_p1.read().is_01())? sc_lv<12>(): sc_biguint<12>(ap_const_lv12_34) * sc_biguint<5>(mul4_fu_335_p1.read());
}

void d_sum::thread_mul_fu_405_p1() {
    mul_fu_405_p1 =  (sc_lv<5>) (mul_fu_405_p10.read());
}

void d_sum::thread_mul_fu_405_p10() {
    mul_fu_405_p10 = esl_zext<12,5>(ix_9_reg_573.read());
}

void d_sum::thread_mul_fu_405_p2() {
    mul_fu_405_p2 = (!ap_const_lv12_34.is_01() || !mul_fu_405_p1.read().is_01())? sc_lv<12>(): sc_biguint<12>(ap_const_lv12_34) * sc_biguint<5>(mul_fu_405_p1.read());
}

void d_sum::thread_p_s_fu_307_p3() {
    p_s_fu_307_p3 = (!tmp_70_fu_295_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_70_fu_295_p2.read()[0].to_bool())? ixstart_17_fu_301_p2.read(): ixstart_16_fu_289_p2.read());
}

void d_sum::thread_p_shl10_cast_fu_363_p1() {
    p_shl10_cast_fu_363_p1 = esl_zext<7,6>(p_shl10_fu_355_p3.read());
}

void d_sum::thread_p_shl10_fu_355_p3() {
    p_shl10_fu_355_p3 = esl_concat<3,3>(tmp_97_fu_351_p1.read(), ap_const_lv3_0);
}

void d_sum::thread_p_shl11_cast_fu_375_p1() {
    p_shl11_cast_fu_375_p1 = esl_zext<7,4>(p_shl11_fu_367_p3.read());
}

void d_sum::thread_p_shl11_fu_367_p3() {
    p_shl11_fu_367_p3 = esl_concat<3,1>(tmp_97_fu_351_p1.read(), ap_const_lv1_0);
}

void d_sum::thread_p_shl8_cast_fu_445_p1() {
    p_shl8_cast_fu_445_p1 = esl_zext<7,4>(p_shl8_fu_437_p3.read());
}

void d_sum::thread_p_shl8_fu_437_p3() {
    p_shl8_fu_437_p3 = esl_concat<3,1>(tmp_95_fu_421_p1.read(), ap_const_lv1_0);
}

void d_sum::thread_p_shl_cast_fu_433_p1() {
    p_shl_cast_fu_433_p1 = esl_zext<7,6>(p_shl_fu_425_p3.read());
}

void d_sum::thread_p_shl_fu_425_p3() {
    p_shl_fu_425_p3 = esl_concat<3,3>(tmp_95_fu_421_p1.read(), ap_const_lv3_0);
}

void d_sum::thread_s12_fu_258_p3() {
    s12_fu_258_p3 = (!tmp_94_fu_240_p3.read()[0].is_01())? sc_lv<64>(): ((tmp_94_fu_240_p3.read()[0].to_bool())? s_4_fu_248_p2.read(): s_16_cast_fu_254_p1.read());
}

void d_sum::thread_s_11_fu_236_p1() {
    s_11_fu_236_p1 = X_q0.read().range(37-1, 0);
}

void d_sum::thread_s_13_fu_493_p2() {
    s_13_fu_493_p2 = (!s_1_reg_142.read().is_01() || !X_q0.read().is_01())? sc_lv<64>(): (sc_biguint<64>(s_1_reg_142.read()) + sc_biguint<64>(X_q0.read()));
}

void d_sum::thread_s_14_fu_519_p2() {
    s_14_fu_519_p2 = (s_13_fu_493_p2.read() | ap_const_lv64_FFFFFFE000000000);
}

void d_sum::thread_s_16_cast_fu_254_p1() {
    s_16_cast_fu_254_p1 = esl_zext<64,37>(s_11_fu_236_p1.read());
}

void d_sum::thread_s_18_cast_fu_505_p2() {
    s_18_cast_fu_505_p2 = (!tmp_100_fu_481_p1.read().is_01() || !tmp_99_fu_477_p1.read().is_01())? sc_lv<38>(): (sc_biguint<38>(tmp_100_fu_481_p1.read()) + sc_biguint<38>(tmp_99_fu_477_p1.read()));
}

void d_sum::thread_s_20_cast_fu_525_p1() {
    s_20_cast_fu_525_p1 = esl_zext<64,37>(s_5_fu_499_p2.read());
}

void d_sum::thread_s_2_fu_529_p3() {
    s_2_fu_529_p3 = (!tmp_103_fu_511_p3.read()[0].is_01())? sc_lv<64>(): ((tmp_103_fu_511_p3.read()[0].to_bool())? s_14_fu_519_p2.read(): s_20_cast_fu_525_p1.read());
}

void d_sum::thread_s_4_fu_248_p2() {
    s_4_fu_248_p2 = (X_q0.read() | ap_const_lv64_FFFFFFE000000000);
}

void d_sum::thread_s_5_fu_499_p2() {
    s_5_fu_499_p2 = (!tmp_102_fu_489_p1.read().is_01() || !tmp_101_fu_485_p1.read().is_01())? sc_lv<37>(): (sc_biguint<37>(tmp_102_fu_489_p1.read()) + sc_biguint<37>(tmp_101_fu_485_p1.read()));
}

void d_sum::thread_tmp_100_fu_481_p1() {
    tmp_100_fu_481_p1 = X_q0.read().range(38-1, 0);
}

void d_sum::thread_tmp_101_fu_485_p1() {
    tmp_101_fu_485_p1 = s_1_reg_142.read().range(37-1, 0);
}

void d_sum::thread_tmp_102_fu_489_p1() {
    tmp_102_fu_489_p1 = X_q0.read().range(37-1, 0);
}

void d_sum::thread_tmp_103_fu_511_p3() {
    tmp_103_fu_511_p3 = s_18_cast_fu_505_p2.read().range(37, 37);
}

void d_sum::thread_tmp_143_cast_fu_458_p1() {
    tmp_143_cast_fu_458_p1 = esl_zext<7,5>(tmp_52_fu_455_p1.read());
}

void d_sum::thread_tmp_146_cast_fu_388_p1() {
    tmp_146_cast_fu_388_p1 = esl_zext<7,5>(tmp_53_fu_385_p1.read());
}

void d_sum::thread_tmp_52_fu_455_p1() {
    tmp_52_fu_455_p1 = esl_sext<5,4>(tmp_96_reg_609.read());
}

void d_sum::thread_tmp_53_fu_385_p1() {
    tmp_53_fu_385_p1 = esl_sext<5,4>(tmp_98_reg_599.read());
}

void d_sum::thread_tmp_64_fu_315_p1() {
    tmp_64_fu_315_p1 = esl_zext<64,3>(iy_reg_119.read());
}

void d_sum::thread_tmp_66_fu_449_p2() {
    tmp_66_fu_449_p2 = (!p_shl_cast_fu_433_p1.read().is_01() || !p_shl8_cast_fu_445_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(p_shl_cast_fu_433_p1.read()) - sc_biguint<7>(p_shl8_cast_fu_445_p1.read()));
}

void d_sum::thread_tmp_67_fu_283_p2() {
    tmp_67_fu_283_p2 = (!ixstart_reg_153.read().is_01() || !ap_const_lv32_7FFFFFF9.is_01())? sc_lv<1>(): (sc_bigint<32>(ixstart_reg_153.read()) > sc_bigint<32>(ap_const_lv32_7FFFFFF9));
}

void d_sum::thread_tmp_69_fu_379_p2() {
    tmp_69_fu_379_p2 = (!p_shl10_cast_fu_363_p1.read().is_01() || !p_shl11_cast_fu_375_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(p_shl10_cast_fu_363_p1.read()) - sc_biguint<7>(p_shl11_cast_fu_375_p1.read()));
}

void d_sum::thread_tmp_70_fu_295_p2() {
    tmp_70_fu_295_p2 = (!ixstart_16_fu_289_p2.read().is_01() || !ap_const_lv32_1D.is_01())? sc_lv<1>(): (sc_bigint<32>(ixstart_16_fu_289_p2.read()) > sc_bigint<32>(ap_const_lv32_1D));
}

void d_sum::thread_tmp_71_fu_472_p1() {
    tmp_71_fu_472_p1 = esl_sext<64,32>(ixstart_4_reg_186.read());
}

void d_sum::thread_tmp_94_fu_240_p3() {
    tmp_94_fu_240_p3 = X_q0.read().range(37, 37);
}

void d_sum::thread_tmp_95_fu_421_p1() {
    tmp_95_fu_421_p1 = grp_fu_199_p2.read().range(3-1, 0);
}

void d_sum::thread_tmp_97_fu_351_p1() {
    tmp_97_fu_351_p1 = grp_fu_199_p2.read().range(3-1, 0);
}

void d_sum::thread_tmp_99_fu_477_p1() {
    tmp_99_fu_477_p1 = s_1_reg_142.read().range(38-1, 0);
}

void d_sum::thread_tmp_fu_216_p1() {
    tmp_fu_216_p1 = ix_reg_131.read().range(5-1, 0);
}

void d_sum::thread_tmp_s_fu_220_p1() {
    tmp_s_fu_220_p1 = esl_zext<64,3>(indvars_iv1_reg_96.read());
}

void d_sum::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond1_fu_204_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(tmp_67_fu_283_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_phi_mux_b3_phi_fu_178_p4.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state21;
            } else if ((esl_seteq<1,1,1>(tmp_67_fu_283_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_phi_mux_b3_phi_fu_178_p4.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(exitcond_fu_270_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<22>) ("XXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

