// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "g_sum.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic g_sum::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic g_sum::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<26> g_sum::ap_ST_fsm_state1 = "1";
const sc_lv<26> g_sum::ap_ST_fsm_state2 = "10";
const sc_lv<26> g_sum::ap_ST_fsm_state3 = "100";
const sc_lv<26> g_sum::ap_ST_fsm_state4 = "1000";
const sc_lv<26> g_sum::ap_ST_fsm_state5 = "10000";
const sc_lv<26> g_sum::ap_ST_fsm_state6 = "100000";
const sc_lv<26> g_sum::ap_ST_fsm_state7 = "1000000";
const sc_lv<26> g_sum::ap_ST_fsm_state8 = "10000000";
const sc_lv<26> g_sum::ap_ST_fsm_state9 = "100000000";
const sc_lv<26> g_sum::ap_ST_fsm_state10 = "1000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state11 = "10000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state12 = "100000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<26> g_sum::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<32> g_sum::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> g_sum::ap_const_lv32_1 = "1";
const sc_lv<1> g_sum::ap_const_lv1_0 = "0";
const sc_lv<32> g_sum::ap_const_lv32_2 = "10";
const sc_lv<32> g_sum::ap_const_lv32_3 = "11";
const sc_lv<1> g_sum::ap_const_lv1_1 = "1";
const sc_lv<32> g_sum::ap_const_lv32_D = "1101";
const sc_lv<32> g_sum::ap_const_lv32_17 = "10111";
const sc_lv<32> g_sum::ap_const_lv32_18 = "11000";
const sc_lv<32> g_sum::ap_const_lv32_19 = "11001";
const sc_lv<5> g_sum::ap_const_lv5_0 = "00000";
const sc_lv<7> g_sum::ap_const_lv7_4 = "100";
const sc_lv<8> g_sum::ap_const_lv8_FF = "11111111";
const sc_lv<7> g_sum::ap_const_lv7_5 = "101";
const sc_lv<5> g_sum::ap_const_lv5_10 = "10000";
const sc_lv<5> g_sum::ap_const_lv5_1 = "1";
const sc_lv<8> g_sum::ap_const_lv8_5 = "101";
const sc_lv<7> g_sum::ap_const_lv7_1 = "1";
const sc_lv<32> g_sum::ap_const_lv32_25 = "100101";
const sc_lv<64> g_sum::ap_const_lv64_FFFFFFE000000000 = "1111111111111111111111111110000000000000000000000000000000000000";
const sc_lv<32> g_sum::ap_const_lv32_7FFFFFEF = "1111111111111111111111111101111";
const sc_lv<32> g_sum::ap_const_lv32_10 = "10000";
const sc_lv<32> g_sum::ap_const_lv32_4F = "1001111";
const sc_lv<32> g_sum::ap_const_lv32_FFFFFFC1 = "11111111111111111111111111000001";
const sc_lv<16> g_sum::ap_const_lv16_CD = "11001101";
const sc_lv<32> g_sum::ap_const_lv32_A = "1010";
const sc_lv<32> g_sum::ap_const_lv32_F = "1111";
const bool g_sum::ap_const_boolean_1 = true;

g_sum::g_sum(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lenetSynthMatlab_g8j_U38 = new lenetSynthMatlab_g8j<1,11,7,4,7>("lenetSynthMatlab_g8j_U38");
    lenetSynthMatlab_g8j_U38->clk(ap_clk);
    lenetSynthMatlab_g8j_U38->reset(ap_rst);
    lenetSynthMatlab_g8j_U38->start(grp_fu_195_ap_start);
    lenetSynthMatlab_g8j_U38->done(grp_fu_195_ap_done);
    lenetSynthMatlab_g8j_U38->din0(grp_fu_195_p0);
    lenetSynthMatlab_g8j_U38->din1(grp_fu_195_p1);
    lenetSynthMatlab_g8j_U38->ce(ap_var_for_const0);
    lenetSynthMatlab_g8j_U38->dout(grp_fu_195_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_X_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( tmp_s_fu_216_p1 );
    sensitive << ( tmp_39_fu_402_p1 );

    SC_METHOD(thread_X_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state25 );

    SC_METHOD(thread_Y_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_34_fu_307_p1 );

    SC_METHOD(thread_Y_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Y_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( s_1_reg_138 );

    SC_METHOD(thread_Y_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_262_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_200_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_b6_phi_fu_174_p4);
    sensitive << ( b6_reg_169 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_200_p2 );

    SC_METHOD(thread_exitcond1_fu_200_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( iy_reg_115 );

    SC_METHOD(thread_exitcond_fu_262_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( indvars_iv_reg_103 );
    sensitive << ( ix_1_reg_160 );

    SC_METHOD(thread_grp_fu_195_ap_start);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_262_p2 );
    sensitive << ( ap_phi_mux_b6_phi_fu_174_p4 );
    sensitive << ( tmp_36_fu_275_p2 );

    SC_METHOD(thread_grp_fu_195_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_262_p2 );
    sensitive << ( ap_phi_mux_b6_phi_fu_174_p4 );
    sensitive << ( tmp_36_fu_275_p2 );
    sensitive << ( ix_1_reg_160 );

    SC_METHOD(thread_grp_fu_195_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_262_p2 );
    sensitive << ( ap_phi_mux_b6_phi_fu_174_p4 );
    sensitive << ( tmp_36_fu_275_p2 );

    SC_METHOD(thread_i_fu_312_p2);
    sensitive << ( iy_reg_115 );

    SC_METHOD(thread_indvars_iv_next2_fu_206_p2);
    sensitive << ( indvars_iv1_reg_92 );

    SC_METHOD(thread_indvars_iv_next_fu_318_p2);
    sensitive << ( indvars_iv_reg_103 );

    SC_METHOD(thread_ix_4_fu_221_p2);
    sensitive << ( ix_reg_127 );

    SC_METHOD(thread_ix_5_fu_268_p2);
    sensitive << ( ix_1_reg_160 );

    SC_METHOD(thread_ixstart_10_cast_fu_359_p1);
    sensitive << ( ixstart_6_fu_353_p2 );

    SC_METHOD(thread_ixstart_6_fu_353_p2);
    sensitive << ( tmp_55_fu_324_p2 );
    sensitive << ( tmp_29_fu_349_p1 );

    SC_METHOD(thread_ixstart_7_fu_281_p2);
    sensitive << ( ixstart9_reg_149 );

    SC_METHOD(thread_ixstart_8_fu_293_p2);
    sensitive << ( ixstart9_reg_149 );

    SC_METHOD(thread_ixstart_9_cast_fu_398_p1);
    sensitive << ( ixstart_fu_392_p2 );

    SC_METHOD(thread_ixstart_cast_fu_227_p2);
    sensitive << ( tmp_reg_475 );

    SC_METHOD(thread_ixstart_fu_392_p2);
    sensitive << ( tmp_53_fu_363_p2 );
    sensitive << ( tmp_28_fu_388_p1 );

    SC_METHOD(thread_mul4_fu_333_p1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( mul4_fu_333_p10 );

    SC_METHOD(thread_mul4_fu_333_p10);
    sensitive << ( ix_5_reg_503 );

    SC_METHOD(thread_mul4_fu_333_p2);
    sensitive << ( mul4_fu_333_p1 );

    SC_METHOD(thread_mul_fu_372_p1);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( mul_fu_372_p10 );

    SC_METHOD(thread_mul_fu_372_p10);
    sensitive << ( ix_5_reg_503 );

    SC_METHOD(thread_mul_fu_372_p2);
    sensitive << ( mul_fu_372_p1 );

    SC_METHOD(thread_p_s_fu_299_p3);
    sensitive << ( ixstart_7_fu_281_p2 );
    sensitive << ( tmp_38_fu_287_p2 );
    sensitive << ( ixstart_8_fu_293_p2 );

    SC_METHOD(thread_s_2_fu_459_p3);
    sensitive << ( tmp_61_fu_441_p3 );
    sensitive << ( s_7_fu_449_p2 );
    sensitive << ( s_8_cast_fu_455_p1 );

    SC_METHOD(thread_s_3_fu_244_p2);
    sensitive << ( X_q0 );

    SC_METHOD(thread_s_4_cast_fu_250_p1);
    sensitive << ( s_4_fu_232_p1 );

    SC_METHOD(thread_s_4_fu_232_p1);
    sensitive << ( X_q0 );

    SC_METHOD(thread_s_5_fu_254_p3);
    sensitive << ( tmp_52_fu_236_p3 );
    sensitive << ( s_3_fu_244_p2 );
    sensitive << ( s_4_cast_fu_250_p1 );

    SC_METHOD(thread_s_6_cast_fu_435_p2);
    sensitive << ( tmp_58_fu_411_p1 );
    sensitive << ( tmp_57_fu_407_p1 );

    SC_METHOD(thread_s_6_fu_423_p2);
    sensitive << ( X_q0 );
    sensitive << ( s_1_reg_138 );

    SC_METHOD(thread_s_7_fu_449_p2);
    sensitive << ( s_6_fu_423_p2 );

    SC_METHOD(thread_s_8_cast_fu_455_p1);
    sensitive << ( s_8_fu_429_p2 );

    SC_METHOD(thread_s_8_fu_429_p2);
    sensitive << ( tmp_60_fu_419_p1 );
    sensitive << ( tmp_59_fu_415_p1 );

    SC_METHOD(thread_tmp_28_fu_388_p1);
    sensitive << ( tmp_54_fu_378_p4 );

    SC_METHOD(thread_tmp_29_fu_349_p1);
    sensitive << ( tmp_56_fu_339_p4 );

    SC_METHOD(thread_tmp_34_fu_307_p1);
    sensitive << ( iy_reg_115 );

    SC_METHOD(thread_tmp_36_fu_275_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_262_p2 );
    sensitive << ( ap_phi_mux_b6_phi_fu_174_p4 );
    sensitive << ( ixstart9_reg_149 );

    SC_METHOD(thread_tmp_38_fu_287_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_262_p2 );
    sensitive << ( ap_phi_mux_b6_phi_fu_174_p4 );
    sensitive << ( tmp_36_fu_275_p2 );
    sensitive << ( ixstart_7_fu_281_p2 );

    SC_METHOD(thread_tmp_39_fu_402_p1);
    sensitive << ( ixstart_4_reg_182 );

    SC_METHOD(thread_tmp_52_fu_236_p3);
    sensitive << ( X_q0 );

    SC_METHOD(thread_tmp_53_fu_363_p2);
    sensitive << ( grp_fu_195_p2 );

    SC_METHOD(thread_tmp_54_fu_378_p4);
    sensitive << ( mul_fu_372_p2 );

    SC_METHOD(thread_tmp_55_fu_324_p2);
    sensitive << ( grp_fu_195_p2 );

    SC_METHOD(thread_tmp_56_fu_339_p4);
    sensitive << ( mul4_fu_333_p2 );

    SC_METHOD(thread_tmp_57_fu_407_p1);
    sensitive << ( s_1_reg_138 );

    SC_METHOD(thread_tmp_58_fu_411_p1);
    sensitive << ( X_q0 );

    SC_METHOD(thread_tmp_59_fu_415_p1);
    sensitive << ( s_1_reg_138 );

    SC_METHOD(thread_tmp_60_fu_419_p1);
    sensitive << ( X_q0 );

    SC_METHOD(thread_tmp_61_fu_441_p3);
    sensitive << ( s_6_cast_fu_435_p2 );

    SC_METHOD(thread_tmp_fu_212_p1);
    sensitive << ( ix_reg_127 );

    SC_METHOD(thread_tmp_s_fu_216_p1);
    sensitive << ( indvars_iv1_reg_92 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_200_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_262_p2 );
    sensitive << ( ap_phi_mux_b6_phi_fu_174_p4 );
    sensitive << ( tmp_36_fu_275_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "g_sum_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, X_address0, "(port)X_address0");
    sc_trace(mVcdFile, X_ce0, "(port)X_ce0");
    sc_trace(mVcdFile, X_q0, "(port)X_q0");
    sc_trace(mVcdFile, Y_address0, "(port)Y_address0");
    sc_trace(mVcdFile, Y_ce0, "(port)Y_ce0");
    sc_trace(mVcdFile, Y_we0, "(port)Y_we0");
    sc_trace(mVcdFile, Y_d0, "(port)Y_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvars_iv_next2_fu_206_p2, "indvars_iv_next2_fu_206_p2");
    sc_trace(mVcdFile, indvars_iv_next2_reg_470, "indvars_iv_next2_reg_470");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_212_p1, "tmp_fu_212_p1");
    sc_trace(mVcdFile, tmp_reg_475, "tmp_reg_475");
    sc_trace(mVcdFile, exitcond1_fu_200_p2, "exitcond1_fu_200_p2");
    sc_trace(mVcdFile, ix_4_fu_221_p2, "ix_4_fu_221_p2");
    sc_trace(mVcdFile, ix_4_reg_485, "ix_4_reg_485");
    sc_trace(mVcdFile, ixstart_cast_fu_227_p2, "ixstart_cast_fu_227_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, s_5_fu_254_p3, "s_5_fu_254_p3");
    sc_trace(mVcdFile, ix_5_fu_268_p2, "ix_5_fu_268_p2");
    sc_trace(mVcdFile, ix_5_reg_503, "ix_5_reg_503");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, exitcond_fu_262_p2, "exitcond_fu_262_p2");
    sc_trace(mVcdFile, p_s_fu_299_p3, "p_s_fu_299_p3");
    sc_trace(mVcdFile, ap_phi_mux_b6_phi_fu_174_p4, "ap_phi_mux_b6_phi_fu_174_p4");
    sc_trace(mVcdFile, tmp_36_fu_275_p2, "tmp_36_fu_275_p2");
    sc_trace(mVcdFile, i_fu_312_p2, "i_fu_312_p2");
    sc_trace(mVcdFile, indvars_iv_next_fu_318_p2, "indvars_iv_next_fu_318_p2");
    sc_trace(mVcdFile, ixstart_10_cast_fu_359_p1, "ixstart_10_cast_fu_359_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ixstart_9_cast_fu_398_p1, "ixstart_9_cast_fu_398_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, s_2_fu_459_p3, "s_2_fu_459_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, indvars_iv1_reg_92, "indvars_iv1_reg_92");
    sc_trace(mVcdFile, indvars_iv_reg_103, "indvars_iv_reg_103");
    sc_trace(mVcdFile, iy_reg_115, "iy_reg_115");
    sc_trace(mVcdFile, ix_reg_127, "ix_reg_127");
    sc_trace(mVcdFile, s_1_reg_138, "s_1_reg_138");
    sc_trace(mVcdFile, ixstart9_reg_149, "ixstart9_reg_149");
    sc_trace(mVcdFile, ixstart_4_reg_182, "ixstart_4_reg_182");
    sc_trace(mVcdFile, ix_1_reg_160, "ix_1_reg_160");
    sc_trace(mVcdFile, b6_reg_169, "b6_reg_169");
    sc_trace(mVcdFile, tmp_s_fu_216_p1, "tmp_s_fu_216_p1");
    sc_trace(mVcdFile, tmp_34_fu_307_p1, "tmp_34_fu_307_p1");
    sc_trace(mVcdFile, tmp_39_fu_402_p1, "tmp_39_fu_402_p1");
    sc_trace(mVcdFile, grp_fu_195_p0, "grp_fu_195_p0");
    sc_trace(mVcdFile, grp_fu_195_p1, "grp_fu_195_p1");
    sc_trace(mVcdFile, s_4_fu_232_p1, "s_4_fu_232_p1");
    sc_trace(mVcdFile, tmp_52_fu_236_p3, "tmp_52_fu_236_p3");
    sc_trace(mVcdFile, s_3_fu_244_p2, "s_3_fu_244_p2");
    sc_trace(mVcdFile, s_4_cast_fu_250_p1, "s_4_cast_fu_250_p1");
    sc_trace(mVcdFile, ixstart_7_fu_281_p2, "ixstart_7_fu_281_p2");
    sc_trace(mVcdFile, tmp_38_fu_287_p2, "tmp_38_fu_287_p2");
    sc_trace(mVcdFile, ixstart_8_fu_293_p2, "ixstart_8_fu_293_p2");
    sc_trace(mVcdFile, grp_fu_195_p2, "grp_fu_195_p2");
    sc_trace(mVcdFile, mul4_fu_333_p1, "mul4_fu_333_p1");
    sc_trace(mVcdFile, mul4_fu_333_p2, "mul4_fu_333_p2");
    sc_trace(mVcdFile, tmp_56_fu_339_p4, "tmp_56_fu_339_p4");
    sc_trace(mVcdFile, tmp_55_fu_324_p2, "tmp_55_fu_324_p2");
    sc_trace(mVcdFile, tmp_29_fu_349_p1, "tmp_29_fu_349_p1");
    sc_trace(mVcdFile, ixstart_6_fu_353_p2, "ixstart_6_fu_353_p2");
    sc_trace(mVcdFile, mul_fu_372_p1, "mul_fu_372_p1");
    sc_trace(mVcdFile, mul_fu_372_p2, "mul_fu_372_p2");
    sc_trace(mVcdFile, tmp_54_fu_378_p4, "tmp_54_fu_378_p4");
    sc_trace(mVcdFile, tmp_53_fu_363_p2, "tmp_53_fu_363_p2");
    sc_trace(mVcdFile, tmp_28_fu_388_p1, "tmp_28_fu_388_p1");
    sc_trace(mVcdFile, ixstart_fu_392_p2, "ixstart_fu_392_p2");
    sc_trace(mVcdFile, tmp_60_fu_419_p1, "tmp_60_fu_419_p1");
    sc_trace(mVcdFile, tmp_59_fu_415_p1, "tmp_59_fu_415_p1");
    sc_trace(mVcdFile, tmp_58_fu_411_p1, "tmp_58_fu_411_p1");
    sc_trace(mVcdFile, tmp_57_fu_407_p1, "tmp_57_fu_407_p1");
    sc_trace(mVcdFile, s_6_cast_fu_435_p2, "s_6_cast_fu_435_p2");
    sc_trace(mVcdFile, s_6_fu_423_p2, "s_6_fu_423_p2");
    sc_trace(mVcdFile, s_8_fu_429_p2, "s_8_fu_429_p2");
    sc_trace(mVcdFile, tmp_61_fu_441_p3, "tmp_61_fu_441_p3");
    sc_trace(mVcdFile, s_7_fu_449_p2, "s_7_fu_449_p2");
    sc_trace(mVcdFile, s_8_cast_fu_455_p1, "s_8_cast_fu_455_p1");
    sc_trace(mVcdFile, grp_fu_195_ap_start, "grp_fu_195_ap_start");
    sc_trace(mVcdFile, grp_fu_195_ap_done, "grp_fu_195_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul4_fu_333_p10, "mul4_fu_333_p10");
    sc_trace(mVcdFile, mul_fu_372_p10, "mul_fu_372_p10");
#endif

    }
}

g_sum::~g_sum() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete lenetSynthMatlab_g8j_U38;
}

void g_sum::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void g_sum::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        b6_reg_169 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        b6_reg_169 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        indvars_iv1_reg_92 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        indvars_iv1_reg_92 = indvars_iv_next2_reg_470.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        indvars_iv_reg_103 = ap_const_lv7_4;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        indvars_iv_reg_103 = indvars_iv_next_fu_318_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        ix_1_reg_160 = ix_5_reg_503.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ix_1_reg_160 = ixstart_cast_fu_227_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ix_reg_127 = ap_const_lv8_FF;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ix_reg_127 = ix_4_reg_485.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        ixstart9_reg_149 = ixstart_4_reg_182.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ixstart9_reg_149 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_phi_mux_b6_phi_fu_174_p4.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_36_fu_275_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        ixstart_4_reg_182 = p_s_fu_299_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        ixstart_4_reg_182 = ixstart_10_cast_fu_359_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        ixstart_4_reg_182 = ixstart_9_cast_fu_398_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        iy_reg_115 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        iy_reg_115 = i_fu_312_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        s_1_reg_138 = s_2_fu_459_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        s_1_reg_138 = s_5_fu_254_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        indvars_iv_next2_reg_470 = indvars_iv_next2_fu_206_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_200_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ix_4_reg_485 = ix_4_fu_221_p2.read();
        tmp_reg_475 = tmp_fu_212_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_0))) {
        ix_5_reg_503 = ix_5_fu_268_p2.read();
    }
}

void g_sum::thread_X_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        X_address0 =  (sc_lv<7>) (tmp_39_fu_402_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        X_address0 =  (sc_lv<7>) (tmp_s_fu_216_p1.read());
    } else {
        X_address0 = "XXXXXXX";
    }
}

void g_sum::thread_X_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read()))) {
        X_ce0 = ap_const_logic_1;
    } else {
        X_ce0 = ap_const_logic_0;
    }
}

void g_sum::thread_Y_address0() {
    Y_address0 =  (sc_lv<4>) (tmp_34_fu_307_p1.read());
}

void g_sum::thread_Y_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Y_ce0 = ap_const_logic_1;
    } else {
        Y_ce0 = ap_const_logic_0;
    }
}

void g_sum::thread_Y_d0() {
    Y_d0 = s_1_reg_138.read();
}

void g_sum::thread_Y_we0() {
    if ((esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        Y_we0 = ap_const_logic_1;
    } else {
        Y_we0 = ap_const_logic_0;
    }
}

void g_sum::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void g_sum::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void g_sum::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void g_sum::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void g_sum::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void g_sum::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void g_sum::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void g_sum::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void g_sum::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(exitcond1_fu_200_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void g_sum::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void g_sum::thread_ap_phi_mux_b6_phi_fu_174_p4() {
    ap_phi_mux_b6_phi_fu_174_p4 = b6_reg_169.read();
}

void g_sum::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond1_fu_200_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void g_sum::thread_exitcond1_fu_200_p2() {
    exitcond1_fu_200_p2 = (!iy_reg_115.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(iy_reg_115.read() == ap_const_lv5_10);
}

void g_sum::thread_exitcond_fu_262_p2() {
    exitcond_fu_262_p2 = (!ix_1_reg_160.read().is_01() || !indvars_iv_reg_103.read().is_01())? sc_lv<1>(): sc_lv<1>(ix_1_reg_160.read() == indvars_iv_reg_103.read());
}

void g_sum::thread_grp_fu_195_ap_start() {
    if (((esl_seteq<1,1,1>(ap_phi_mux_b6_phi_fu_174_p4.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(tmp_36_fu_275_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_phi_mux_b6_phi_fu_174_p4.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())))) {
        grp_fu_195_ap_start = ap_const_logic_1;
    } else {
        grp_fu_195_ap_start = ap_const_logic_0;
    }
}

void g_sum::thread_grp_fu_195_p0() {
    grp_fu_195_p0 = (!ix_1_reg_160.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(ix_1_reg_160.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void g_sum::thread_grp_fu_195_p1() {
    grp_fu_195_p1 =  (sc_lv<4>) (ap_const_lv7_5);
}

void g_sum::thread_i_fu_312_p2() {
    i_fu_312_p2 = (!iy_reg_115.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(iy_reg_115.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void g_sum::thread_indvars_iv_next2_fu_206_p2() {
    indvars_iv_next2_fu_206_p2 = (!indvars_iv1_reg_92.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvars_iv1_reg_92.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void g_sum::thread_indvars_iv_next_fu_318_p2() {
    indvars_iv_next_fu_318_p2 = (!indvars_iv_reg_103.read().is_01() || !ap_const_lv7_5.is_01())? sc_lv<7>(): (sc_biguint<7>(indvars_iv_reg_103.read()) + sc_biguint<7>(ap_const_lv7_5));
}

void g_sum::thread_ix_4_fu_221_p2() {
    ix_4_fu_221_p2 = (!ap_const_lv8_5.is_01() || !ix_reg_127.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_5) + sc_biguint<8>(ix_reg_127.read()));
}

void g_sum::thread_ix_5_fu_268_p2() {
    ix_5_fu_268_p2 = (!ix_1_reg_160.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(ix_1_reg_160.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void g_sum::thread_ixstart_10_cast_fu_359_p1() {
    ixstart_10_cast_fu_359_p1 = esl_zext<32,7>(ixstart_6_fu_353_p2.read());
}

void g_sum::thread_ixstart_6_fu_353_p2() {
    ixstart_6_fu_353_p2 = (!tmp_55_fu_324_p2.read().is_01() || !tmp_29_fu_349_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_55_fu_324_p2.read()) + sc_bigint<7>(tmp_29_fu_349_p1.read()));
}

void g_sum::thread_ixstart_7_fu_281_p2() {
    ixstart_7_fu_281_p2 = (!ixstart9_reg_149.read().is_01() || !ap_const_lv32_10.is_01())? sc_lv<32>(): (sc_biguint<32>(ixstart9_reg_149.read()) + sc_biguint<32>(ap_const_lv32_10));
}

void g_sum::thread_ixstart_8_fu_293_p2() {
    ixstart_8_fu_293_p2 = (!ixstart9_reg_149.read().is_01() || !ap_const_lv32_FFFFFFC1.is_01())? sc_lv<32>(): (sc_biguint<32>(ixstart9_reg_149.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFC1));
}

void g_sum::thread_ixstart_9_cast_fu_398_p1() {
    ixstart_9_cast_fu_398_p1 = esl_zext<32,7>(ixstart_fu_392_p2.read());
}

void g_sum::thread_ixstart_cast_fu_227_p2() {
    ixstart_cast_fu_227_p2 = (!ap_const_lv7_1.is_01() || !tmp_reg_475.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_1) + sc_biguint<7>(tmp_reg_475.read()));
}

void g_sum::thread_ixstart_fu_392_p2() {
    ixstart_fu_392_p2 = (!tmp_53_fu_363_p2.read().is_01() || !tmp_28_fu_388_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp_53_fu_363_p2.read()) + sc_bigint<7>(tmp_28_fu_388_p1.read()));
}

void g_sum::thread_mul4_fu_333_p1() {
    mul4_fu_333_p1 =  (sc_lv<7>) (mul4_fu_333_p10.read());
}

void g_sum::thread_mul4_fu_333_p10() {
    mul4_fu_333_p10 = esl_zext<16,7>(ix_5_reg_503.read());
}

void g_sum::thread_mul4_fu_333_p2() {
    mul4_fu_333_p2 = (!ap_const_lv16_CD.is_01() || !mul4_fu_333_p1.read().is_01())? sc_lv<16>(): sc_biguint<16>(ap_const_lv16_CD) * sc_biguint<7>(mul4_fu_333_p1.read());
}

void g_sum::thread_mul_fu_372_p1() {
    mul_fu_372_p1 =  (sc_lv<7>) (mul_fu_372_p10.read());
}

void g_sum::thread_mul_fu_372_p10() {
    mul_fu_372_p10 = esl_zext<16,7>(ix_5_reg_503.read());
}

void g_sum::thread_mul_fu_372_p2() {
    mul_fu_372_p2 = (!ap_const_lv16_CD.is_01() || !mul_fu_372_p1.read().is_01())? sc_lv<16>(): sc_biguint<16>(ap_const_lv16_CD) * sc_biguint<7>(mul_fu_372_p1.read());
}

void g_sum::thread_p_s_fu_299_p3() {
    p_s_fu_299_p3 = (!tmp_38_fu_287_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_38_fu_287_p2.read()[0].to_bool())? ixstart_8_fu_293_p2.read(): ixstart_7_fu_281_p2.read());
}

void g_sum::thread_s_2_fu_459_p3() {
    s_2_fu_459_p3 = (!tmp_61_fu_441_p3.read()[0].is_01())? sc_lv<64>(): ((tmp_61_fu_441_p3.read()[0].to_bool())? s_7_fu_449_p2.read(): s_8_cast_fu_455_p1.read());
}

void g_sum::thread_s_3_fu_244_p2() {
    s_3_fu_244_p2 = (X_q0.read() | ap_const_lv64_FFFFFFE000000000);
}

void g_sum::thread_s_4_cast_fu_250_p1() {
    s_4_cast_fu_250_p1 = esl_zext<64,37>(s_4_fu_232_p1.read());
}

void g_sum::thread_s_4_fu_232_p1() {
    s_4_fu_232_p1 = X_q0.read().range(37-1, 0);
}

void g_sum::thread_s_5_fu_254_p3() {
    s_5_fu_254_p3 = (!tmp_52_fu_236_p3.read()[0].is_01())? sc_lv<64>(): ((tmp_52_fu_236_p3.read()[0].to_bool())? s_3_fu_244_p2.read(): s_4_cast_fu_250_p1.read());
}

void g_sum::thread_s_6_cast_fu_435_p2() {
    s_6_cast_fu_435_p2 = (!tmp_58_fu_411_p1.read().is_01() || !tmp_57_fu_407_p1.read().is_01())? sc_lv<38>(): (sc_biguint<38>(tmp_58_fu_411_p1.read()) + sc_biguint<38>(tmp_57_fu_407_p1.read()));
}

void g_sum::thread_s_6_fu_423_p2() {
    s_6_fu_423_p2 = (!s_1_reg_138.read().is_01() || !X_q0.read().is_01())? sc_lv<64>(): (sc_biguint<64>(s_1_reg_138.read()) + sc_biguint<64>(X_q0.read()));
}

void g_sum::thread_s_7_fu_449_p2() {
    s_7_fu_449_p2 = (s_6_fu_423_p2.read() | ap_const_lv64_FFFFFFE000000000);
}

void g_sum::thread_s_8_cast_fu_455_p1() {
    s_8_cast_fu_455_p1 = esl_zext<64,37>(s_8_fu_429_p2.read());
}

void g_sum::thread_s_8_fu_429_p2() {
    s_8_fu_429_p2 = (!tmp_60_fu_419_p1.read().is_01() || !tmp_59_fu_415_p1.read().is_01())? sc_lv<37>(): (sc_biguint<37>(tmp_60_fu_419_p1.read()) + sc_biguint<37>(tmp_59_fu_415_p1.read()));
}

void g_sum::thread_tmp_28_fu_388_p1() {
    tmp_28_fu_388_p1 = esl_sext<7,6>(tmp_54_fu_378_p4.read());
}

void g_sum::thread_tmp_29_fu_349_p1() {
    tmp_29_fu_349_p1 = esl_sext<7,6>(tmp_56_fu_339_p4.read());
}

void g_sum::thread_tmp_34_fu_307_p1() {
    tmp_34_fu_307_p1 = esl_zext<64,5>(iy_reg_115.read());
}

void g_sum::thread_tmp_36_fu_275_p2() {
    tmp_36_fu_275_p2 = (!ixstart9_reg_149.read().is_01() || !ap_const_lv32_7FFFFFEF.is_01())? sc_lv<1>(): (sc_bigint<32>(ixstart9_reg_149.read()) > sc_bigint<32>(ap_const_lv32_7FFFFFEF));
}

void g_sum::thread_tmp_38_fu_287_p2() {
    tmp_38_fu_287_p2 = (!ixstart_7_fu_281_p2.read().is_01() || !ap_const_lv32_4F.is_01())? sc_lv<1>(): (sc_bigint<32>(ixstart_7_fu_281_p2.read()) > sc_bigint<32>(ap_const_lv32_4F));
}

void g_sum::thread_tmp_39_fu_402_p1() {
    tmp_39_fu_402_p1 = esl_sext<64,32>(ixstart_4_reg_182.read());
}

void g_sum::thread_tmp_52_fu_236_p3() {
    tmp_52_fu_236_p3 = X_q0.read().range(37, 37);
}

void g_sum::thread_tmp_53_fu_363_p2() {
    tmp_53_fu_363_p2 = (!ap_const_lv7_4.is_01())? sc_lv<7>(): grp_fu_195_p2.read() << (unsigned short)ap_const_lv7_4.to_uint();
}

void g_sum::thread_tmp_54_fu_378_p4() {
    tmp_54_fu_378_p4 = mul_fu_372_p2.read().range(15, 10);
}

void g_sum::thread_tmp_55_fu_324_p2() {
    tmp_55_fu_324_p2 = (!ap_const_lv7_4.is_01())? sc_lv<7>(): grp_fu_195_p2.read() << (unsigned short)ap_const_lv7_4.to_uint();
}

void g_sum::thread_tmp_56_fu_339_p4() {
    tmp_56_fu_339_p4 = mul4_fu_333_p2.read().range(15, 10);
}

void g_sum::thread_tmp_57_fu_407_p1() {
    tmp_57_fu_407_p1 = s_1_reg_138.read().range(38-1, 0);
}

void g_sum::thread_tmp_58_fu_411_p1() {
    tmp_58_fu_411_p1 = X_q0.read().range(38-1, 0);
}

void g_sum::thread_tmp_59_fu_415_p1() {
    tmp_59_fu_415_p1 = s_1_reg_138.read().range(37-1, 0);
}

void g_sum::thread_tmp_60_fu_419_p1() {
    tmp_60_fu_419_p1 = X_q0.read().range(37-1, 0);
}

void g_sum::thread_tmp_61_fu_441_p3() {
    tmp_61_fu_441_p3 = s_6_cast_fu_435_p2.read().range(37, 37);
}

void g_sum::thread_tmp_fu_212_p1() {
    tmp_fu_212_p1 = ix_reg_127.read().range(7-1, 0);
}

void g_sum::thread_tmp_s_fu_216_p1() {
    tmp_s_fu_216_p1 = esl_zext<64,5>(indvars_iv1_reg_92.read());
}

void g_sum::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond1_fu_200_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_phi_mux_b6_phi_fu_174_p4.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_36_fu_275_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state25;
            } else if ((esl_seteq<1,1,1>(ap_phi_mux_b6_phi_fu_174_p4.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(exitcond_fu_262_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(tmp_36_fu_275_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<26>) ("XXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

