// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module c_sum (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        y_address0,
        y_ce0,
        y_we0,
        y_d0,
        y_q0
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [4:0] y_address0;
output   y_ce0;
output   y_we0;
output  [31:0] y_d0;
input  [31:0] y_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] x_address0;
reg x_ce0;
reg[4:0] y_address0;
reg y_ce0;
reg y_we0;
reg[31:0] y_d0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] k_29_fu_144_p2;
reg   [2:0] k_29_reg_366;
wire    ap_CS_fsm_state2;
wire   [6:0] tmp_fu_174_p2;
reg   [6:0] tmp_reg_371;
wire   [0:0] exitcond4_fu_138_p2;
wire   [2:0] b_k_13_fu_190_p2;
reg   [2:0] b_k_13_reg_379;
wire    ap_CS_fsm_state3;
wire   [63:0] tmp_150_fu_205_p1;
reg   [63:0] tmp_150_reg_384;
wire   [0:0] exitcond3_fu_184_p2;
wire   [2:0] k_30_fu_216_p2;
reg   [2:0] k_30_reg_397;
wire    ap_CS_fsm_state5;
wire  signed [8:0] tmp_cast_fu_254_p1;
reg  signed [8:0] tmp_cast_reg_402;
wire   [0:0] exitcond2_fu_210_p2;
wire   [2:0] b_k_14_fu_264_p2;
reg   [2:0] b_k_14_reg_410;
wire    ap_CS_fsm_state6;
wire  signed [6:0] tmp_151_fu_294_p2;
reg  signed [6:0] tmp_151_reg_415;
wire   [0:0] exitcond1_fu_258_p2;
wire   [8:0] tmp1_fu_304_p2;
reg   [8:0] tmp1_reg_420;
wire   [2:0] c_k_2_fu_323_p2;
reg   [2:0] c_k_2_reg_428;
wire    ap_CS_fsm_state7;
wire   [0:0] exitcond_fu_317_p2;
reg   [4:0] y_addr_5_reg_438;
reg   [31:0] x_load_5_reg_443;
wire    ap_CS_fsm_state8;
reg   [31:0] y_load_reg_448;
wire   [31:0] grp_fu_134_p2;
reg   [31:0] tmp_156_reg_453;
wire    ap_CS_fsm_state13;
reg   [2:0] k_reg_79;
reg   [2:0] b_k_reg_90;
wire    ap_CS_fsm_state4;
reg   [2:0] k_1_reg_101;
reg   [2:0] b_k_1_reg_112;
reg   [2:0] c_k_reg_123;
wire    ap_CS_fsm_state14;
wire   [63:0] tmp_153_fu_344_p1;
wire   [63:0] tmp_155_fu_358_p1;
wire    ap_CS_fsm_state9;
wire   [5:0] p_shl_fu_150_p3;
wire   [3:0] p_shl9_fu_162_p3;
wire   [6:0] p_shl_cast_fu_158_p1;
wire   [6:0] p_shl9_cast_fu_170_p1;
wire   [6:0] b_k_cast7_fu_180_p1;
wire   [6:0] tmp_149_fu_196_p2;
wire  signed [31:0] tmp_155_cast_fu_201_p1;
wire   [1:0] tmp_157_fu_222_p1;
wire   [6:0] p_shl10_fu_226_p3;
wire   [2:0] tmp_158_fu_238_p2;
wire   [7:0] p_shl10_cast_fu_234_p1;
wire   [7:0] p_shl11_cast_fu_244_p1;
wire   [7:0] tmp_s_fu_248_p2;
wire   [5:0] p_shl12_fu_270_p3;
wire   [3:0] p_shl13_fu_282_p3;
wire   [6:0] p_shl12_cast_fu_278_p1;
wire   [6:0] p_shl13_cast_fu_290_p1;
wire  signed [8:0] tmp_157_cast_fu_300_p1;
wire   [5:0] c_k_cast3_fu_313_p1;
wire   [5:0] tmp2_fu_329_p2;
wire   [8:0] tmp2_cast_fu_335_p1;
wire   [8:0] tmp_152_fu_339_p2;
wire   [6:0] c_k_cast4_fu_309_p1;
wire   [6:0] tmp_154_fu_349_p2;
wire  signed [31:0] tmp_161_cast_fu_354_p1;
reg   [13:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
end

lenetSynthMatlab_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lenetSynthMatlab_bkb_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(y_load_reg_448),
    .din1(x_load_5_reg_443),
    .ce(1'b1),
    .dout(grp_fu_134_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_fu_317_p2 == 1'd1))) begin
        b_k_1_reg_112 <= b_k_14_reg_410;
    end else if (((exitcond2_fu_210_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        b_k_1_reg_112 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_138_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        b_k_reg_90 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        b_k_reg_90 <= b_k_13_reg_379;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_258_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        c_k_reg_123 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        c_k_reg_123 <= c_k_2_reg_428;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_138_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        k_1_reg_101 <= 3'd0;
    end else if (((exitcond1_fu_258_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        k_1_reg_101 <= k_30_reg_397;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_184_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        k_reg_79 <= k_29_reg_366;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_reg_79 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        b_k_13_reg_379 <= b_k_13_fu_190_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        b_k_14_reg_410 <= b_k_14_fu_264_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        c_k_2_reg_428 <= c_k_2_fu_323_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        k_29_reg_366 <= k_29_fu_144_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        k_30_reg_397 <= k_30_fu_216_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_258_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp1_reg_420[8 : 1] <= tmp1_fu_304_p2[8 : 1];
        tmp_151_reg_415[6 : 1] <= tmp_151_fu_294_p2[6 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_184_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_150_reg_384[31 : 0] <= tmp_150_fu_205_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_156_reg_453 <= grp_fu_134_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_210_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_cast_reg_402[8 : 1] <= tmp_cast_fu_254_p1[8 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_138_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_reg_371[6 : 1] <= tmp_fu_174_p2[6 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_load_5_reg_443 <= x_q0;
        y_load_reg_448 <= y_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_317_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        y_addr_5_reg_438 <= tmp_155_fu_358_p1;
    end
end

always @ (*) begin
    if ((((exitcond2_fu_210_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_fu_210_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        x_address0 = tmp_153_fu_344_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_address0 = tmp_150_fu_205_p1;
    end else begin
        x_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state7))) begin
        x_ce0 = 1'b1;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        y_address0 = y_addr_5_reg_438;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        y_address0 = tmp_155_fu_358_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        y_address0 = tmp_150_reg_384;
    end else begin
        y_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7))) begin
        y_ce0 = 1'b1;
    end else begin
        y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        y_d0 = tmp_156_reg_453;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        y_d0 = x_q0;
    end else begin
        y_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state4))) begin
        y_we0 = 1'b1;
    end else begin
        y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond4_fu_138_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond3_fu_184_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond2_fu_210_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((exitcond1_fu_258_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (exitcond_fu_317_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign b_k_13_fu_190_p2 = (b_k_reg_90 + 3'd1);

assign b_k_14_fu_264_p2 = (b_k_1_reg_112 + 3'd1);

assign b_k_cast7_fu_180_p1 = b_k_reg_90;

assign c_k_2_fu_323_p2 = (c_k_reg_123 + 3'd1);

assign c_k_cast3_fu_313_p1 = c_k_reg_123;

assign c_k_cast4_fu_309_p1 = c_k_reg_123;

assign exitcond1_fu_258_p2 = ((b_k_1_reg_112 == 3'd5) ? 1'b1 : 1'b0);

assign exitcond2_fu_210_p2 = ((k_1_reg_101 == 3'd4) ? 1'b1 : 1'b0);

assign exitcond3_fu_184_p2 = ((b_k_reg_90 == 3'd6) ? 1'b1 : 1'b0);

assign exitcond4_fu_138_p2 = ((k_reg_79 == 3'd5) ? 1'b1 : 1'b0);

assign exitcond_fu_317_p2 = ((c_k_reg_123 == 3'd6) ? 1'b1 : 1'b0);

assign k_29_fu_144_p2 = (k_reg_79 + 3'd1);

assign k_30_fu_216_p2 = (k_1_reg_101 + 3'd1);

assign p_shl10_cast_fu_234_p1 = p_shl10_fu_226_p3;

assign p_shl10_fu_226_p3 = {{tmp_157_fu_222_p1}, {5'd0}};

assign p_shl11_cast_fu_244_p1 = tmp_158_fu_238_p2;

assign p_shl12_cast_fu_278_p1 = p_shl12_fu_270_p3;

assign p_shl12_fu_270_p3 = {{b_k_1_reg_112}, {3'd0}};

assign p_shl13_cast_fu_290_p1 = p_shl13_fu_282_p3;

assign p_shl13_fu_282_p3 = {{b_k_1_reg_112}, {1'd0}};

assign p_shl9_cast_fu_170_p1 = p_shl9_fu_162_p3;

assign p_shl9_fu_162_p3 = {{k_reg_79}, {1'd0}};

assign p_shl_cast_fu_158_p1 = p_shl_fu_150_p3;

assign p_shl_fu_150_p3 = {{k_reg_79}, {3'd0}};

assign tmp1_fu_304_p2 = ($signed(tmp_157_cast_fu_300_p1) + $signed(tmp_cast_reg_402));

assign tmp2_cast_fu_335_p1 = tmp2_fu_329_p2;

assign tmp2_fu_329_p2 = (c_k_cast3_fu_313_p1 + 6'd30);

assign tmp_149_fu_196_p2 = (tmp_reg_371 + b_k_cast7_fu_180_p1);

assign tmp_150_fu_205_p1 = $unsigned(tmp_155_cast_fu_201_p1);

assign tmp_151_fu_294_p2 = (p_shl12_cast_fu_278_p1 - p_shl13_cast_fu_290_p1);

assign tmp_152_fu_339_p2 = (tmp2_cast_fu_335_p1 + tmp1_reg_420);

assign tmp_153_fu_344_p1 = tmp_152_fu_339_p2;

assign tmp_154_fu_349_p2 = ($signed(tmp_151_reg_415) + $signed(c_k_cast4_fu_309_p1));

assign tmp_155_cast_fu_201_p1 = $signed(tmp_149_fu_196_p2);

assign tmp_155_fu_358_p1 = $unsigned(tmp_161_cast_fu_354_p1);

assign tmp_157_cast_fu_300_p1 = tmp_151_fu_294_p2;

assign tmp_157_fu_222_p1 = k_1_reg_101[1:0];

assign tmp_158_fu_238_p2 = k_1_reg_101 << 3'd1;

assign tmp_161_cast_fu_354_p1 = $signed(tmp_154_fu_349_p2);

assign tmp_cast_fu_254_p1 = $signed(tmp_s_fu_248_p2);

assign tmp_fu_174_p2 = (p_shl_cast_fu_158_p1 - p_shl9_cast_fu_170_p1);

assign tmp_s_fu_248_p2 = (p_shl10_cast_fu_234_p1 - p_shl11_cast_fu_244_p1);

always @ (posedge ap_clk) begin
    tmp_reg_371[0] <= 1'b0;
    tmp_150_reg_384[63:32] <= 32'b00000000000000000000000000000000;
    tmp_cast_reg_402[0] <= 1'b0;
    tmp_151_reg_415[0] <= 1'b0;
    tmp1_reg_420[0] <= 1'b0;
end

endmodule //c_sum
